RT-Thread/packages

- README.md
> [完善]：packages repo 说明文档完善。

- iot/Kconfig
- iot/cJSON/Kconfig
- iot/cJSON/package.json
- language/Kconfig
- language/jerryscript/Kconfig
- language/jerryscript/package.json
[添加]：在iot目录下增加cJSON包。
[修改]：修改language目录下的jerryscript包为git类型包并测试通过。
--
> add cjson & jerryscript packages

- tools/Kconfig
- tools/SystemView/Kconfig
- tools/SystemView/package.json
Segger SystemView for analysis and trace the RTOS.
> [tool][SystemView] Add new package. Segger SystemView

- iot/WiFi/wiced/Kconfig
- iot/WiFi/wiced/package.json
[Update] update wiced wifi config  
[Update] Update wlan-wiced package sha value
> update wiced wifi config

- iot/WiFi/Kconfig
- iot/WiFi/wlanmarvell/Kconfig
- iot/WiFi/wlanmarvell/package.json
- iot/WiFi/wlanwiced/Kconfig
- iot/WiFi/wlanwiced/package.json
Note:
Directory name of WiFi must be consistent in Kconfig and package.json
> [Fix] Fix WiFi config error

- system/persimmon/Kconfig
- system/persimmon/package.json
[packages][persimmon][update] update sha value, update Kconfig
> [packages][persimmon][update] update sha value, update Kconfig

- iot/WebTerminal/Kconfig
- iot/WebTerminal/package.json
- iot/mongoose/Kconfig
- iot/mongoose/package.json
- language/micropython/Kconfig
- language/micropython/package.json
- tools/CmBacktrace/Kconfig
- tools/CmBacktrace/package.json
- tools/EasyLogger/Kconfig
- tools/EasyLogger/package.json
- mongoose
- WebTerminal
- CmBacktrace
- EasyLogger
- micropython
> Add version choice for some pkgs

- iot/pahomqtt/Kconfig
add max pahomqtt subscribe topic handlers
> add max pahomqtt subscribe topic handlers

- iot/WiFi/wlan_wiced/package.json
[wlan_wiced] Update commit SHA1
> [wlan_wiced] Update commit SHA1

- iot/GAgent/Kconfig
- iot/GAgent/package.json
- iot/Kconfig
> add GAgent to iot package

- iot/GAgent/Kconfig
> fix GAgent Kconfig bug

- iot/WiFi/wlan_wiced/Kconfig
- iot/WiFi/wlan_wiced/package.json
update for supporting Multi-version
> [iot/WiFi] update for supporting Multi-version

- iot/Kconfig
- iot/coap/Kconfig
- iot/coap/package.json
add coap/Kconfig
add coap/package.json
> [iot] add coap package

- iot/Kconfig
- iot/nopoll/Kconfig
- iot/nopoll/package.json
[iot] Add nopoll websocket package
> [iot] Add nopoll support

- iot/GAgent/Kconfig
- iot/pahomqtt/Kconfig
update GAgent && pahomqtt kconfig
> update GAgent && pahomqtt kconfig

- misc/fastlz/Kconfig
- misc/fastlz/package.json
> [fastlz] update

- misc/miniLZO/Kconfig
- misc/miniLZO/package.json
> [miniLZO] update

- language/micropython/package.json
Update the micropython repository address and the stable version of the SHA value.
> [micropython]: update the micropython package index

- security/tinycrypt/Kconfig
- security/tinycrypt/package.json
> [tinycrypt]update kconfig, add v.1.1.0

- misc/CanFestival/Kconfig
- misc/CanFestival/package.json
- misc/Kconfig
Add CanFestival(CANopen) package and servo control example
> Add CanFestival package

- misc/MultiButton/Kconfig
- misc/MultiButton/package.json
> [MultiButton] fix memset error and update v1.0.2 . |  修复memset错误并更新为1.0.2版本. 

- iot/Kconfig
- iot/onenet/Kconfig
- iot/onenet/package.json
> [add] onenet kconfig index

- misc/samples/Kconfig
> modify led configuration

- misc/samples/package.json
> 【修改】：删除空链接

- misc/samples/Kconfig
> Update samples Kconfig

- tools/SystemView/Kconfig
> [tools][SystemView]Modify the SystemView and hook dependencies.

- tools/SystemView/package.json
> [tools][SystemView] Add new site definition for latest version

- peripherals/Kconfig
- peripherals/realtek_ameba/Kconfig
- peripherals/realtek_ameba/package.json
> add realtek_ameba package

- misc/samples/Kconfig
【添加】：network samples 添加 tcp client by select 例程
> 【添加】：network samples 添加 tcp client by select 例程

- iot/Kconfig
- iot/at_device/Kconfig
- iot/at_device/package.json
> [at_device] add at device Kconfig & package.json

- iot/netutils/Kconfig
> [netutils] update Kconfig, depends on lwip

- iot/pahomqtt/Kconfig
> [pahomqtt] 增加 mqtt 线程堆栈配置选项

- misc/samples/Kconfig
> [samples] add a network samples webclient.c

- tools/SystemView/Kconfig
> Update Kconfig of SystemView package

- tools/SystemView/Kconfig
> SystemView: default disable post mortem analysis mode

- security/mbedtls/Kconfig
[mbedtls] add debug log switch
> [mbedtls] add debug log switch

- iot/webclient/Kconfig
> [webclient] update Kconfig

- security/mbedtls/Kconfig
> [mbedtls] 增加 CA 证书处理

- peripherals/Kconfig
- peripherals/sht2x/Kconfig
- peripherals/sht2x/package.json
> 【添加】sht20 软件包

- peripherals/sht2x/Kconfig
- peripherals/sht2x/package.json
> 【完善】索引、功能选项

- peripherals/sht2x/Kconfig
- peripherals/sht2x/package.json
> 【完善】软件包sht2x索引与功能显示

- iot/webclient/Kconfig
> [webclient] add libc support

- iot/at_device/Kconfig
> [at_device] add AT components select

- misc/optparse/package.json
[update] update optparse v1.0.0 to zip download. | 更新optparse包v1.0.0为zip下载方式.
> [update] update optparse v1.0.0 to zip download. 

- iot/at_device/Kconfig
> Add ec20 support

- security/mbedtls/Kconfig
- security/mbedtls/package.json
> 【更新】mbedtls 索引

- security/mbedtls/package.json
> 【更新】mbedtls release 索引

- iot/iot_cloud/ali-iotkit/Kconfig
- iot/iot_cloud/ali-iotkit/package.json
> 【更新】ali-iotkit 包索引

- iot/iot_cloud/ali-iotkit/Kconfig
> 【更新】ali-iotkit release 包版本号

- README.md
> 【添加】：ci 状态显示

- iot/at_device/Kconfig
- iot/at_device/package.json
- iot/webclient/Kconfig
> [webclient] update webclient default version

- iot/netutils/Kconfig
> [netutils][ntp] delete ntp select POSIX

- peripherals/u8g2/Kconfig
- peripherals/u8g2/package.json
把 U8g2 的库和 examples 分开，为不同的 example 添加了单独的选项。
> Seperate examples from library

- iot/wiznet/Kconfig
> [wiznet] update Kconfig for ping configure

- misc/Kconfig
- misc/TinyFrame/Kconfig
- misc/TinyFrame/package.json
TinyFrame是一个基于串口的通讯协议,github:<https://github.com/XXXXzzzz000/TinyFrame>
> [misc][TinyFrame] add TinyFrame package.

- iot/at_device/Kconfig
- iot/at_device/package.json
> [at_device] update package version

- language/jerryscript/Kconfig
- system/gui_engine/Kconfig
> update jerryscript/Kconfig gui_engine/Kconfig

- peripherals/Kconfig
- peripherals/mpu6xxx/Kconfig
- peripherals/mpu6xxx/package.json
> [peripherals][mpu6xxx] add mpu6xxx package.

- iot/Kconfig
- iot/webnet/Kconfig
- iot/webnet/package.json
> [webnet]add webnet package index

- iot/webnet/package.json
> [webnet] update kconfig

- iot/iot_cloud/Kconfig
- iot/iot_cloud/tencent-iotkit/Kconfig
- iot/iot_cloud/tencent-iotkit/package.json
tencent iot package based on rt-thread first commit
> tencent iot package based on rt-thread first commit

- iot/webclient/Kconfig
> [webclient] update Kconfig SAL TLS Configuration

- peripherals/button/Kconfig
- peripherals/button/package.json
Comments use English comments, style is similar to rtt, button source has been modified, others slightly modified.
> update button drive v1.0.1

- misc/quicklz/Kconfig
[misc/quicklz/Kconfig] 更新默认的压缩级别，默认设置为 3（RT_OTA 打包工具只支持 level 3 压缩）
> [misc/quicklz/Kconfig] 更新默认的压缩级别，默认设置为 3（RT_OTA 打包工具只支持 level 3 压缩）

- iot/netutils/Kconfig
> [iot/netutils/iperf]Add libc dependency

- system/gui_engine/Kconfig
> update gui_engine/Kconfig 增加 RGB888 像素格式配置选项

- peripherals/u8g2/Kconfig
添加了4个 examples, 硬件/软件- I2C/SPI
> Split examples (sw_i2c, hw_i2c, sw_spi, hw_spi)

- peripherals/u8g2/Kconfig
- peripherals/u8g2/package.json
发布 v1.1.0: 
- 完成了 I2C, SPI, 8080, 6800, gpio, delay 的移植;
- 添加 sw_i2c, hw_i2c, sw_spi, hw_spi, st7920 例程;
> Release v1.1.0

- language/jerryscript/Kconfig
> update language/jerryscript/Kconfig 增加选中依赖选项

- security/mbedtls/Kconfig
> 【添加】mbedtls amazon 认证支持选项

- system/cairo/Kconfig
- system/gui_engine/Kconfig
> update cairo/Kconfig  gui_engine/Kconfig

- iot/webclient/Kconfig
> [webclient] add debug log configuration

- iot/at_device/Kconfig
> [iot][at_device] add SIMComm sim76xx support

- security/tinycrypt/Kconfig
[security/tinycrypt] 增加 AES CBC 例程配置
> [security/tinycrypt] 增加 AES CBC 例程配置

- misc/nnom/Kconfig
- misc/nnom/package.json
- set default version to 'latest'
- update manuals url
> Update NNoM configurations

- peripherals/rosserial/Kconfig
- peripherals/rosserial/package.json
- 添加 rosserial 对 TCP 的移植
- 添加 TCP 的例程
- 发布了 v1.0.0
> [rosserial] Add TCP support

- iot/NimBLE/Kconfig
- 增加对 NRF51822 和 Nrf52840 的支持
- 格式化TAB符号
> 【修改】NimBLE 增加对 NRF51822 和 Nrf52840 的支持

- iot/webnet/Kconfig
- iot/webnet/package.json
> [webnet] update webnet package v2.0.1

- iot/iot_cloud/azure-iot-sdk/Kconfig
- iot/iot_cloud/azure-iot-sdk/package.json
> 【修改】：添加 azure 云软件包 1.2.9 版本

- peripherals/sensors/Kconfig
- peripherals/sensors/df220/Kconfig
- peripherals/sensors/df220/package.json
rtt中如下提交必须更新才能使用此sensor。
Add new sensor type and vendor type. #2587
> Add df220 force sensor driver package.

- peripherals/u8g2/Kconfig
- peripherals/u8g2/package.json
- 添加了 C++ wrapper，简化了库的使用
- 更新了新 api 下的 example
- 发布了 v2.0.0
> [u8g2] v2.0.0 released

- iot/netutils/Kconfig
> [netutils] adapt netdev ping change

- peripherals/u8g2/Kconfig
- 添加了 1 个 game 例程
- 添加了 10 个 full buffer 例程
> U8g2 11 examples

- peripherals/u8g2/Kconfig
- 添加了 27 个 page buffer 例子
- 添加了 6 个 u8x8 例子
> [u8g2] more examples

- peripherals/u8g2/Kconfig
- peripherals/u8g2/package.json
- 添加了用户界面按键输入
- 增加了几个新设备支持
- 添加了 50 个例子
- 发布了 v2.1.0
> [u8g2] v2.1.0 released

- peripherals/Kconfig
- peripherals/MotionDriver2RTT/Kconfig
- peripherals/MotionDriver2RTT/package.json
> 添加MotionDriver2RTT软件包

- peripherals/sensors/Kconfig
- peripherals/sensors/bh1750/Kconfig
- peripherals/sensors/bh1750/package.json
Hi Guo，对齐格式已修复，请审核，如有问题请指正指出，谢谢！
> 增加基于sensor框架的BH1750FVI传感器驱动软件包

- peripherals/ad7746/Kconfig
- peripherals/ad7746/package.json
- Kconfig 配置默认 i2c 地址
- 添加了电容读取例程
- 添加了电容读取例程(带扩容)
- 添加了读写例程对十六进制的支持
- 发布了 v1.0.0
> Upstream ad7746 v1.0.0

- peripherals/Kconfig
- peripherals/pca9685/Kconfig
- peripherals/pca9685/package.json
可以通过I2C总线控制PCA9685产生PWM信号
在stm32f767测试成功
> [new]添加PCA9685软件包

- peripherals/Kconfig
- peripherals/i2c_tools/Kconfig
- peripherals/i2c_tools/package.json
方便调试 i2c 设备的小工具：
- 扫描 i2c 设备
- 读写寄存器
- 支持硬件I2C/软件I2C
> [new] add package i2c-tools

- peripherals/u8g2/Kconfig
> [u8g2] add new game T-Rex

- iot/webclient/Kconfig
- iot/webclient/package.json
> [webclient] release v2.1.0

- peripherals/i2c_tools/Kconfig
- peripherals/i2c_tools/package.json
- 支持硬件 I2C
- 支持软件 I2C
- 修复软件 I2C 扫描等待时间过长的问题
- 添加 I2C ACK 超时选项
- 发布 V1.0.0
> Upstream i2c tools v1.0.0

- iot/at_device/Kconfig
- iot/at_device/ec20/Kconfig
- iot/at_device/esp8266/Kconfig
- iot/at_device/m26/Kconfig
- iot/at_device/rw007/Kconfig
- iot/at_device/sim76xx/Kconfig
- iot/at_device/sim800c/Kconfig
- iot/at_device/v1.x.x/Kconfig
> [at_device] update AT socket Multi-client support index

- language/micropython/Kconfig
> 【添加】micropython network.WLAN 功能和 machine.LCD 功能

- tools/adbd/Kconfig
- tools/adbd/package.json
> 【更新】adbd 软件包索引。

- language/micropython/Kconfig
> [micropython] add machine rtc/pwm/adc module index

- iot/netutils/Kconfig
- iot/netutils/package.json
> [update] netutils v1.1.0 config

- misc/nnom/package.json
Change version 0.2.0-beta to 0.2.0
> Change version 0.2.0-beta to 0.2.0

- misc/libann/Kconfig
从 Flash 加载模型，这样没有 SD 卡的板子也可以 benchmark
> [libann] Add example that stores data in flash

- misc/libann/Kconfig
如果使用了从文件系统加载数据集，那么需要 DFS 和 libc 支持
> [libann] Auto select DFS and libc support

- peripherals/sensors/rt3020/Kconfig
- peripherals/sensors/rt3020/package.json
> Add rt3020 sensor driver

- language/micropython/Kconfig
> [micropython] add machine.WDT and machine.Timer module

- iot/pahomqtt/Kconfig
- iot/pahomqtt/package.json
> [pahomqtt] update V1.1.0

- system/littlefs/Kconfig
- system/littlefs/package.json
2.change littlefs lookahead = 128
> 1.add littlefs v2.0.5.

- peripherals/nrf24l01/Kconfig
为这个软件包增加两个功能选项
Add two functional options to this package
Signed-off-by: Willian Chan <chentingwei@rt-thread.com>
> Add two functional options to this package

- peripherals/nrf24l01/Kconfig
Signed-off-by: Willian Chan <chentingwei@rt-thread.com>
> Fix some errors

- iot/at_device/Kconfig
- iot/at_device/package.json
> [at_device] update at_device V2.0.0

- peripherals/touch/Kconfig
- peripherals/touch/ft6206/Kconfig
- peripherals/touch/ft6206/package.json
add ft6206 package index
Signed-off-by: Willian Chan <chentingwei@rt-thread.com>
> add ft6206 package index

- peripherals/sensors/ds18b20/package.json
> fix DS18B20 package name

- iot/Kconfig
- iot/protobuf-c/Kconfig
- iot/protobuf-c/package.json
> [new] Add package protobuf-c

- iot/Kconfig
- iot/onnx-parser/Kconfig
- iot/onnx-parser/package.json
通用机器学习模型 onnx 的加载库，这样在 RT-Thread 就能加载各种主流机器学习的库
> [new] add package onnx-parser

- language/micropython/Kconfig
- language/micropython/package.json
> 【更新】mpy 索引

- misc/Kconfig
- misc/elapack/Kconfig
- misc/elapack/package.json
> [new] add package elapack

- misc/elapack/Kconfig
> [misc][elapack] use libc

- iot/iot_cloud/tencent-iothub/Kconfig
- iot/iot_cloud/tencent-iothub/package.json
> 增加腾讯云物联网软件包索引v3.0.2

- peripherals/sensors/Kconfig
- peripherals/sensors/dht11/Kconfig
- peripherals/sensors/dht11/package.json
[peripheral][sensors] [add] dht11 sensor
> [peripheral][sensors] [add] dht11 sensor

- iot/onnx-backend/Kconfig
1. 增加 onnx-backend 的依赖项 onnx-parser
2. 增加例程：从文件读取模型权值
3. 增加例程：从文件读取模型和权值并自动计算得到结果
> [iot][onnx-backend] Add two more examples

- iot/iot_cloud/ali-iotkit/Kconfig
- iot/iot_cloud/ali-iotkit/package.json
[iot][ali-iotkit] 增加 v3.0.1 版本
> [iot][ali-iotkit] 增加 v3.0.1 版本

- iot/iot_cloud/Kconfig
- iot/iot_cloud/jiot-c-sdk/Kconfig
- iot/iot_cloud/jiot-c-sdk/package.json
> 1.添加极光IoT 的jiot-c-sdk的软件包索引

- iot/iot_cloud/jiot-c-sdk/Kconfig
> 1.sdk取消对系统RTC库的依赖

- iot/webclient/Kconfig
> [webclient] format code and add file download config

- misc/vt100/Kconfig
- misc/vt100/package.json
- peripherals/i2c_tools/Kconfig
> [misc][vt100] v1.0.0 released

- iot/onnx-backend/Kconfig
- iot/onnx-backend/package.json
- iot/onnx-parser/Kconfig
- iot/onnx-parser/package.json
- iot/protobuf-c/Kconfig
- iot/protobuf-c/package.json
- misc/libann/Kconfig
- misc/libann/package.json
相互依赖的数学软件包发布 v1.0.0
- libann: ANN 神经网络
- protobuf-c: Google protocol buffer 解析
- onnx-parser: onnx 模型解析
- onnx-backend: onnx 模型后端
> [pkg] v1.0.0 released for math correlated pkgs

- misc/elapack/Kconfig
添加线性方程组求解例程 AX = B (兼容 Matlab/Octave)
```
A = [3,  4, 1; 
6, 10, 2; 
5,  3, 2]
B = [4, 3, 22, 5; 
5, 3,  2, 5; 
3, 4,  5, 3]
X = linsolve(A, B)
```
结果：
```
X =
12.5000     9.5000   144.0000    19.5000
-1.5000    -1.5000   -21.0000    -2.5000
-27.5000   -19.5000  -326.0000   -43.5000
```
> [misc][elapack] Add linear equation solver example

- misc/elapack/Kconfig
添加求解矩阵特征值和特征向量的例子
```
A = [ 4,  3,   1,  4,  2, 23;
6,  3,  -2,  3,  5,  8;
1,  3,   6,  2,  3,  2;
2,  5,   6,  7,  4,  4;
4,  6, -88,  6,  4,  6;
2,  1,  44, 54,  3,  2];
[V, D, W] = eig(A)
```
结果:
```
A = 
4.000000000000000000 3.000000000000000000 1.000000000000000000 4.000000000000000000 2.000000000000000000 23.000000000000000000  
6.000000000000000000 3.000000000000000000 -2.000000000000000000 3.000000000000000000 5.000000000000000000 8.000000000000000000  
1.000000000000000000 3.000000000000000000 6.000000000000000000 2.000000000000000000 3.000000000000000000 2.000000000000000000   
2.000000000000000000 5.000000000000000000 6.000000000000000000 7.000000000000000000 4.000000000000000000 4.000000000000000000   
4.000000000000000000 6.000000000000000000 -88.000000000000000000 …
```
> [misc][elapack] Add eigen examples

- misc/elapack/Kconfig
添加矩阵分解相关例程：
- 添加矩阵 LU 分解例程
- 添加矩阵 QR 分解例程
- 添加矩阵 SVD 分解例程
> [misc][elapack] Add matrix decomposition examples

- iot/wiznet/Kconfig
> [wiznet] update wiznet select soft_timer

- misc/elapack/Kconfig
添加了一些综合例程：
- 添加状态空间控制例程
- 添加 model predictive control 例程
> [misc][elapack] Add complex examples

- misc/elapack/Kconfig
- misc/elapack/package.json
elapack 发布 v1.0.0，包含 7 个例程：
| Example | Memory |
|----------|-------------|
| linsolve 线性方程组 |  2 KB |
| qr 矩阵 QR 分解 |  2 KB |
| lu 矩阵 LU 分解 |  2 KB |
| svd 矩阵 SVD 分解 |  20 KB |
| eig 特征值和特征向量 | 30 KB |
| model 综合控制模型预测 | 20 KB |
| state 综合状态空间控制 | 800 KB |
> [misc][elapack] v1.0.0 released

- iot/ppp_device/Kconfig
- iot/ppp_device/package.json
> 【增加】PPP DEVICE 软件包的中英文描述

- peripherals/Kconfig
- peripherals/rplidar/Kconfig
- peripherals/rplidar/package.json
> [peripherals][rplidar] Add new package rplidar

- iot/ppp_device/Kconfig
> [ppp_device] add ppp_device select index

- peripherals/rplidar/Kconfig
添加 3 个例程：
- 停止激光雷达扫描
- 复位激光雷达
- 获取激光雷达版本信息
> [peripherals][rplidar] Add more examples

- peripherals/rplidar/Kconfig
添加 2 个例程：
- 激光雷达进入扫描模式
- 激光雷达扫描并获取数据
> [peripherals][rplidar] Add scan example

- iot/ppp_device/Kconfig
> 【增加】SIM800模块支持

- peripherals/rplidar/Kconfig
> [peripherals][rplidar] select libc

- peripherals/rosserial/Kconfig
rosserial 添加更多例程:
- 添加一个 Blink 例程 (订阅 LED 开关的 Empty Message)
- 添加一个 Blink Class 例程 (订阅 LED 开关的 message，并发布设置闪烁时间的 service)
- 添加一个 Button 例程 (发布按键状态的 Message)
- 添加一个 订阅发布 例程 (同时 publish 和 subscribe)
- 添加一个 日志记录 例程
- 添加一个 TF 例程 (发布 TF message)
- 添加两个 Service 例程
> [peripherals][rosserial] Add more examples

- peripherals/u8g2/Kconfig
发现中午提了个 BUG，少了个引号，唉，害得张莽找了半天程序 BUG
> [peripherals][u8g2] Fix missing quote

- iot/ppp_device/Kconfig
【增加】DEBUG功能下的RX的数据输出
【增加】DEBUG功能下的TX的数据输出
【增加】DEBUG功能下的丢弃数据的打印输出
【修改】LCP链路监控数据发送间隔
> 增加PPP_DEVICE的DEBUG配置功能

- iot/ppp_device/Kconfig
- iot/ppp_device/package.json
> 【增加】release V1.0.0版本

- peripherals/at24cxx/package.json
原来的软件包长期不更新维护，提交pr无人处理，已基于原软件包更新，修复bug，增加新功能，请求更新软件包地址
> change packages url

- iot/ppp_device/Kconfig
- iot/ppp_device/package.json
> 【修改】PPP_DEVICE的软件包描述

- iot/at_device/Kconfig
- iot/at_device/package.json
> [at_device] update V2.0.1

- iot/webclient/Kconfig
- iot/webclient/package.json
> [webclient] update v2.1.1

- iot/Kconfig
- iot/abup_fota/Kconfig
- iot/abup_fota/package.json
> add abup fota downloader

- tools/nr_micro_shell/Kconfig
- tools/nr_micro_shell/package.json
add nr_micro_shell package to ./tools.
repository:[https://github.com/Nrusher/nr_micro_shell](https://github.com/Nrusher/nr_micro_shell)
> add nr_micro_shell

- iot/mymqtt/Kconfig
- iot/mymqtt/package.json
> 1.提交一种基于paho mqtt新的一种实现方式，命名为mymqtt

- peripherals/Kconfig
- peripherals/as608/Kconfig
- peripherals/as608/package.json
> [peripherals] add as608 packet

- peripherals/sht3x/Kconfig
- peripherals/sht3x/package.json
> add release version v1.0.0

- tools/Kconfig
- tools/lunar_calendar/Kconfig
- tools/lunar_calendar/package.json
A tool to convert a Gregorian calendar date into a lunar calendar.
> add tools/lunar_calendar

- tools/Kconfig
- tools/bs8116a/Kconfig
- tools/bs8116a/package.json
> add tools/bs8116a

- peripherals/as608/Kconfig
- peripherals/as608/package.json
> [peripherals\as608] ver 1.0.1

- iot/Kconfig
- iot/libcurl2rtt/Kconfig
- iot/libcurl2rtt/package.json
简单命令行测试：
GET https 加载本地文件系统中证书
> [更新] 添加 curl 索引

- tools/nr_micro_shell/Kconfig
Fix path errors in nr_micro_shell Kconfig.
> Nr micro shell pr

- iot/Kconfig
- iot/capnp/Kconfig
- iot/capnp/package.json
新年快乐，2020年第一个软件包
https://capnproto.org/capnp-tool.html
为了更高效地存储数据，可以使用 Google 的 protobuf 定义二进制文件格式。
同样的，capnp 也是为了更高效地存储二进制文件，但是相比 protobuf 更加高效，更加轻量级。
- 添加 capnp 在内存 encode & decode 例程
- 添加 capnp 在文件系统上 encode & decode 例程
> [iot][capnp] new package capnp

- iot/webclient/Kconfig
- iot/webclient/package.json
> [webclient] update v2.2.0 version

- iot/iot_cloud/Kconfig
- iot/iot_cloud/ucloud_iot_sdk/Kconfig
- iot/iot_cloud/ucloud_iot_sdk/package.json
> ucloud iot rtthread package

- peripherals/sensors/Kconfig
- peripherals/sensors/gy271/Kconfig
- peripherals/sensors/gy271/package.json
> 添加honeywell 公司的gy271三轴磁力计驱动

- security/trusted-firmware-m/package.json
TFM will release new version in the future, the master branch of TFM
package is going to chase the latest repo.
Signed-off-by: Karl Zhang <karl.zhang@arm.com>
> TFM: Add the latest repo modules

- peripherals/rc522/Kconfig
> [peripherals][rc522] Update Kconfig

- peripherals/sensors/Kconfig
- peripherals/sensors/dhtxx/Kconfig
- peripherals/sensors/dhtxx/package.json
I build a dhtxx package, and have been tested on STM32 with DHT11 and DHT22. Hoping to join ^_^
> Add dhtxx package which support DHTxx one-wire serial sensor

- iot/Kconfig
- iot/rt_cjson_tools/Kconfig
- iot/rt_cjson_tools/package.json
Provide JSON data parsing and perform corresponding actions
> add rt_cjson_tools

- peripherals/sensors/Kconfig
- peripherals/sensors/gp2y10/Kconfig
- peripherals/sensors/gp2y10/package.json
- peripherals/sensors/sgp30/Kconfig
- peripherals/sensors/sgp30/package.json
增加两个传感器驱动软件包，分别是 gp2y10 和 sgp30
> Add gp2y10 and sgp30 sensor packages

- peripherals/Kconfig
- peripherals/rtc/Kconfig
- peripherals/rtc/ds3231/Kconfig
- peripherals/rtc/ds3231/package.json
add rtc driver package for ds3231
> add  ds3231

- system/Kconfig
- system/plccore/Kconfig
- system/plccore/package.json
> Add plccore package index.

- peripherals/sensors/Kconfig
- peripherals/sensors/hdc1000/Kconfig
- peripherals/sensors/hdc1000/package.json
1. add hdc1000 sensor driver package V1.0.0
> add TI hdc1000 sensor driver package

- peripherals/Kconfig
- peripherals/beep/Kconfig
- peripherals/beep/package.json
> Add beep package

- iot/at_device/Kconfig
- iot/at_device/package.json
> [at_device] update v2.0.2

- iot/iot_cloud/joylink/Kconfig
- iot/iot_cloud/joylink/package.json
Signed-off-by: liuxinaliang <liuxianliang@rt-thread.com>
> 【更新】 joylink 选项配置

- peripherals/easyblink/Kconfig
- peripherals/easyblink/package.json
> [easyblink]Update info

- peripherals/sensors/Kconfig
- peripherals/sensors/bmi088/Kconfig
- peripherals/sensors/bmi088/package.json
社区开发小组成员郭明禹
软件包链接: https://github.com/gmyFighting/bmi088
> bmi088 软件包索引

- peripherals/beep/Kconfig
- peripherals/beep/package.json
- peripherals/easyblink/Kconfig
- peripherals/easyblink/package.json
> [beep][easyblink]更新信息

- iot/iot_cloud/joylink/Kconfig
- iot/iot_cloud/joylink/package.json
Signed-off-by: liuxinaliang <liuxianliang@rt-thread.com>
> [update] joylink index

- tools/Kconfig
- tools/UrlEncode/Kconfig
- tools/UrlEncode/package.json
> 添加UrlEncode软件包

- iot/ppp_device/Kconfig
- iot/ppp_device/package.json
* ppp_device support private APN access point
* supprot cmux function
Signed-off-by: liuxinaliang <liuxianliang@rt-thread.com>
> [update] ppp_device support private APN access point

- iot/bc28_mqtt/Kconfig
> [bc28_mqtt] add config items

- peripherals/sensors/Kconfig
- peripherals/sensors/hmc5883/Kconfig
- peripherals/sensors/hmc5883/package.json
> add hmc5883 software package

- peripherals/multi_rtimer/Kconfig
fixed the multi_rtimer PKG_MULTI_RTIMER_PATH ,for the issue which software package load failed.
> fixed the multi_rtimer PKG_MULTI_RTIMER_PATH

- peripherals/Kconfig
- peripherals/can_ymodem/Kconfig
- peripherals/can_ymodem/package.json
> add can_ymodem

- peripherals/sensors/Kconfig
- peripherals/sensors/sr04/Kconfig
- peripherals/sensors/sr04/package.json
> add hc-sr04 driver package index

- misc/vt100/Kconfig
vt100 添加 lsimg 命令例程，直接解码 jpg 并在控制台画出图像：
> [misc][vt100] Add lsimg example

- iot/at_device/Kconfig
- iot/at_device/package.json
> [at_device] update v2.0.3

- iot/iot_cloud/tencent-iot-sdk/Kconfig
- iot/iot_cloud/tencent-iot-sdk/package.json
tencent iot package update to v3.1.3
> tencent iot package update to v3.1.3

- peripherals/sensors/Kconfig
- peripherals/sensors/ccs811/Kconfig
- peripherals/sensors/ccs811/package.json
- peripherals/sensors/dhtxx/package.json
- peripherals/sensors/gp2y10/package.json
- peripherals/sensors/sgp30/package.json
增加 ccs811 气体传感器软件包，已对接 sensor 驱动框架。顺便统一一下之前提交的软件包署名
> [Sensor] Add CCS811 gas sensor driver package

- peripherals/sensors/Kconfig
- peripherals/sensors/pmsxx/Kconfig
- peripherals/sensors/pmsxx/package.json
> [Sesor] Add PMSxx family sensor driver package

- peripherals/Kconfig
- peripherals/PAJ7620/Kconfig
- peripherals/PAJ7620/package.json
add gesture detection module PAJ7620.
> Add PAJ7620 module.

- peripherals/sensors/pmsxx/Kconfig
> [pmsxx] add some config

- peripherals/sensors/pmsxx/Kconfig
> [pms] support select pms sensor type

- peripherals/sensors/Kconfig
- peripherals/sensors/mlx90632/Kconfig
- peripherals/sensors/mlx90632/package.json
> add sensor mlx90632

- misc/crclib/Kconfig
- misc/crclib/package.json
crclib release v1.00 and optimize menuconfig
> Fix crclib

- peripherals/Kconfig
- peripherals/ld3320/Kconfig
- peripherals/ld3320/package.json
增加语音识别芯片LD3320软件包，第一次投软件包，可能会多修改几次脚本
> 增加语音识别芯片LD3320软件包，我第一次提交

- tools/Kconfig
- tools/uMCN/Kconfig
- tools/uMCN/package.json
uMCN is a light-weight and powerful IPC library based on the publisher/subscriber model.
> add uMCN package

- iot/netutils/Kconfig
- iot/netutils/package.json
> [update] release netutils 1.2.0.

- peripherals/nrf5x_sdk/Kconfig
- peripherals/nrf5x_sdk/package.json
fix the Kconfig to the nrf5x_sdk
> [nrf5x_sdk] fix the Kconfig

- peripherals/nrf5x_sdk/Kconfig
> fix the warning about nrf5x

- peripherals/ly68l6400/Kconfig
change ly68l6400 package description in "Kconfig" file
> change Kconfig file

- iot/Kconfig
- iot/btstack/Kconfig
- iot/btstack/package.json
> [iot] add btstack package

- iot/webnet/Kconfig
- iot/webnet/package.json
> [webnet]update v2.0.2

- language/jerryscript/Kconfig
> [ add ] 增加字节码编译功能和字节码加载执行功能使能配置

- peripherals/sensors/Kconfig
- peripherals/sensors/ms5805/Kconfig
- peripherals/sensors/ms5805/package.json
> 添加MS5805传感器

- iot/bc28_mqtt/Kconfig
> [bc28_mqtt] select dependent components

- peripherals/nrf5x_sdk/Kconfig
configure led pins and button pins
> change ble_app_blink kconfig of nrf5x_sdk

- peripherals/nrf5x_sdk/Kconfig
[peripherals][nrf5x_sdk]Kconfig add dis and bas.
> [peripherals][nrf5x_sdk]Kconfig add dis and bas.

- peripherals/touch/Kconfig
- peripherals/touch/ft6236/Kconfig
- peripherals/touch/ft6236/package.json
> add ft6236 packages

- peripherals/sensors/Kconfig
- peripherals/sensors/max31865/Kconfig
- peripherals/sensors/max31865/package.json
Signed-off-by: SimpleInit <63694297@qq.com>
> [add] a package of digital temperature sensor max31865

- multimedia/Kconfig
- multimedia/helix/Kconfig
- multimedia/helix/package.json
> add Helix MP3 Decoder

- system/sqlite/Kconfig
Add version choice to Sqlite in Kconfig
> Add version choice to Sqlite in Kconfig

- peripherals/dm9051/package.json
fixed https://github.com/RT-Thread/packages/commit/a027498c34d7413d7a51aed0f2998cff5e6a61d9#r43568451
> 更新 package.json: 添加 enable 字段

- iot/lorawan_ed_stack/Kconfig
- iot/lorawan_ed_stack/package.json
- peripherals/lora_radio_driver/Kconfig
- peripherals/multi_rtimer/Kconfig
1. add lorawan_ed_stack first version
2. fixed lora-radio-driver lora module
3. update multi_rtimer file struction, now support to stm32l0、stm32l4、stm32wl 、stm32h7
> add lorawan_ed_stack first version

- iot/Kconfig
- peripherals/lora_radio_driver/Kconfig
- peripherals/lora_radio_driver/package.json
- peripherals/multi_rtimer/Kconfig
- peripherals/multi_rtimer/package.json
1. update multi_rtimer released version
2. update lora-radio released version for APT-Pi demo
>  update multi_rtimer released ver and lora-radio released ver

- iot/lorawan_ed_stack/Kconfig
- iot/lorawan_ed_stack/package.json
update lorawan-ed-stack released version for APT-Pi demo
> update lorawan-ed-stack released version

- misc/tetris/Kconfig
- misc/tetris/package.json
http://packages.rt-thread.org/ 官网这里是不更新了吗？
> 稍微修改了一下我的俄罗斯方块

- multimedia/helix/Kconfig
- multimedia/helix/package.json
- peripherals/touch/ft6236/Kconfig
- peripherals/touch/ft6236/package.json
add v1.0.0 for helix and ft6326
> release v1.0.0 for helix and ft6326

- peripherals/nrf5x_sdk/Kconfig
> add nrf5x bas sample config

- iot/WiFi/rw007/Kconfig
- iot/WiFi/rw007/package.json
> 添加v2.0.0选项

- multimedia/Kconfig
- multimedia/touchgfx2rtt/Kconfig
- multimedia/touchgfx2rtt/package.json
> add TouchGFX GUI

- peripherals/ad7746/Kconfig
> [peripherals][ad7746] select cpp

- peripherals/Kconfig
- peripherals/nes/Kconfig
- peripherals/nes/package.json
- tools/Kconfig
- tools/gbk2utf8/Kconfig
- tools/gbk2utf8/package.json
> add gbk2utf8 and nes packages

- iot/lorawan_ed_stack/Kconfig
- iot/lorawan_ed_stack/package.json
lorawan-ed-stack update released 1.0.3
1. add optimize lw1.0.x nwkkey init
> lorawan-ed-stack update released 1.0.3

- iot/Kconfig
- iot/wayz_iotkit/Kconfig
- iot/wayz_iotkit/package.json
First release [wayz_iotkit] v1.0.0 version
> [wayz_iotkit] update v1.0.0 version

- peripherals/Kconfig
- peripherals/vsensor/Kconfig
- peripherals/vsensor/package.json
【增加】虚拟sensor device设备，可以模拟sensor device设备，用于上层应用的调试
> 【增加】虚拟sensor device设备

- peripherals/vsensor/Kconfig
- peripherals/vsensor/package.json
> 【更新】修复虚拟传感器软件包更新问题

- system/openamp/Kconfig
> rename path name

- iot/wayz_iotkit/package.json
> 在RT-Thread Studio软件包上增加描述信息

- system/lwext4/package.json
> modefy lwext4 pkgs

- tools/Kconfig
- tools/mbedtls_bench/Kconfig
- tools/mbedtls_bench/package.json
The mbedtls_bench is a performance test tool of cryptographic algorithms of mbedtls.
> [add] mbedtls_bench

- peripherals/Kconfig
- peripherals/sgm706/Kconfig
- peripherals/sgm706/package.json
> add sgm706 package

- language/micropython/Kconfig
- system/rt_printf/Kconfig
heyuanjie只在代码中增加了宏定义 但是没有在kconfig中增加相关配置 遂予以补充
> add MICROPYTHON_USING_FLOAT_IMPL_FLOAT in kconfig

- tools/Kconfig
- tools/wamr/Kconfig
- tools/wamr/package.json
[add] add wamr package information point to `https://github.com/bytecodealliance/wasm-micro-runtime`
> [add] add wamr package information

- tools/logmgr/Kconfig
> [logmgr] add samples index

- tools/ulog_file/Kconfig
> [ulog_file] update ulog_file index

- tools/logmgr/Kconfig
- tools/logmgr/package.json
- tools/ulog_file/Kconfig
- tools/ulog_file/package.json
> [logmgr][ulog_file] update 1.0.0 version

- tools/logmgr/Kconfig
> [logmgr] update index

- tools/CmBacktrace/Kconfig
【添加】更新 CmBacktrace 支持 CM33 patch
> [add] add CM33 choice for CmBacktrace/Kconfig

- misc/Kconfig
- misc/mcurses/Kconfig
- misc/mcurses/package.json
> [misc] new package mcurses

- misc/Kconfig
- misc/cowsay/Kconfig
- misc/cowsay/package.json
牛年快乐，cowsay 软件包 [CUI]：
msh />cowsay Happy New Year
________________
< Happy New Year >
----------------
\   ^__^
\  (oo)\_______
(__)\       )\/\
||----w |
||     ||
msh />
> [misc] new package cowsay

- tools/Kconfig
- tools/lwlog/Kconfig
- tools/lwlog/package.json
新年快乐，lwlog 软件包 [CUI]：
#define LOG_COLOR (1) // 0: off, 1: on, default: 1
#define LOG_LEVEL (7) // -1: off, 0~7: different log levels, default: 7
#include <rtthread.h>
#include "lwlog.h"
int lwlog_demo(int argc, char const *argv[])
{
lwlog_emerg("This a emerge log.");
lwlog_alert("This a alert log.");
lwlog_crit("This a crit log.");
lwlog_err("This a err log.");
lwlog_warning("This a warning log.");
lwlog_notice("This a notice log.");
lwlog_info("This a info log.");
lwlog_debug("This a debug log.");
return 0;
}
MSH_CMD_EXPORT(lwlog_demo, lwlog demo);
> [tools] new package lwlog

- tools/Kconfig
- tools/anv_trace/Kconfig
- tools/anv_trace/package.json
新年快乐，anv_trace 软件包 [debug]：
RT-Thread 程序追踪软件包，帮助定位程序运行位置。
int anv_trace_example(int argc, char const *argv[])
{
anv_trace_init(stdout);
anv_trace_enter();
anv_traced("Hello %s!", "Debug");
anv_tracei("Hello %s!", "Info");
anv_tracew("Hello %s!", "Warning");
anv_tracee("Hello %s!", "Error");
anv_tracef("Hello %s!", "Fatal");
anv_trace_leave();
anv_trace_quit();
return 0;
}
可以知道程序什么时候进入了哪个函数，有没有顺利退出。
msh />
\ | /
/ | \     4.0.3 build Feb 11 2021
2006 - 2021 Copyright by rt-thread team
msh />anv
anv_trace_example
msh />anv_trace_example
== [MESSAGE] [                 FILENAME: LINE | FUNCTION            ] Begin Trace (1970/01/01 - 00:00:00)
-- [Debug  ] [packages\anv-trace\anv_trace_example.c:   11 | anv_trace_example   ] << entering "anv_trace_example"
-- …
> [tools] new package anv_trace

- tools/Kconfig
- tools/anv_memleak/Kconfig
- tools/anv_memleak/package.json
新年快乐，anv_memleak 软件包 [debug]：
RT-Thread 软件包，帮助检查内存泄漏。
int anv_memleak_example(int argc, char const *argv[])
{
anv_leak_info **leaks;
size_t leaks_count;
anv_leaks_init(stdout);
void *mem = malloc(10);
anv_leaks_quickpeek();
// free(mem);
// anv_leaks_quickpeek();
anv_leaks_stats stats;
anv_leaks_get_stats(&stats);
rt_kprintf("[total] %d allocated, %d freed\n", stats.total_allocated, stats.total_freed);
rt_kprintf("[count] %d malloc, %d free\n", stats.malloc_count, stats.free_count);
rt_kprintf("[count] %d calloc, %d realloc\n", stats.calloc_count, stats.realloc_count);
anv_leaks_get_leaks(&leaks, &leaks_count);
rt_kprintf("\n");
rt_kprintf("[total] %d leaks\n", leaks_count);
for (int i = 0; i < leaks_count; ++i)
{
rt_kprintf("[%s] line %d, %d bytes\n", leaks[i]->filename,  leaks[i]->line, …
> [tools] new package anv_memleak

- tools/Kconfig
- tools/anv_testsuit/Kconfig
- tools/anv_testsuit/package.json
新年快乐，anv_testsuit 软件包 [debug]：
RT-Thread 单元测试框架
#include <rtthread.h>
#include "anv_testsuite.h"
ANV_TESTSUITE_FIXTURE(test_group_1_fixture_1)
{
int a = 10;
expect(a == 10);
int b = 13;
expect(a == b);
}
ANV_TESTSUITE_FIXTURE(test_group_1_fixture_2)
{
}
ANV_TESTSUITE_FIXTURE(test_group_1_fixture_3)
{
expect_msg(0, "rip");
}
ANV_TESTSUITE(test_group_1,
ANV_TESTSUITE_ADD(test_group_1_fixture_1),
ANV_TESTSUITE_ADD(test_group_1_fixture_2),
ANV_TESTSUITE_ADD(test_group_1_fixture_3),
);
ANV_TESTSUITE_FIXTURE(test_group_2_fixture_1)
{
}
ANV_TESTSUITE(test_group_2,
ANV_TESTSUITE_ADD(test_group_2_fixture_1),
);
int anv_testsuit_example(int argc, char const *argv[])
{
ANV_TESTSUITE_BEGIN(stdout);    // optional
ANV_TESTSUITE_RUN(test_group_1, stdout);
ANV_TESTSUITE_RUN(test_group_2, stdout); …
> [tools] new package anv_testsuit

- tools/Kconfig
- tools/anv_bench/Kconfig
- tools/anv_bench/package.json
新年快乐，anv_bench 软件包 [debug]：
RT-Thread 函数性能测试软件包
#include <rtthread.h>
#include <anv_bench.h>
ANV_BENCH_NOINLINE void test_func_a(int *a, int b, int c)
{
*a += (b - c) * 2 + *a;
rt_thread_mdelay(1);
}
ANV_BENCH_NOINLINE int test_func_b(int b, int c)
{
rt_thread_mdelay(2);
return (b + c) / 2;
}
int anv_bench_group_example(int argc, char const *argv[])
{
int a = 0;
rt_kprintf("\n");
ANV_BENCH_BEGIN(stdout, 10, 1000);
ANV_BENCH_ADD(test_func_a, &a, 2, 3);
ANV_BENCH_ADD(test_func_b, 2, 3);
ANV_BENCH_END();
return 0;
}
MSH_CMD_EXPORT(anv_bench_group_example, anv bench group example);
可以看到不同函数执行 1000 次所需时间：
\ | /
/ | \     4.0.3 build Feb 11 2021
2006 - 2021 Copyright by rt-thread team
msh />ac
msh />a
anv_bench_example
msh />anv_bench_example …
> [tools] new package anv bench

- peripherals/sensors/Kconfig
- peripherals/sensors/lis2dh12/Kconfig
- peripherals/sensors/lis2dh12/package.json
添加ST的MEMS型廉价3轴加速度计传感器：lis2dh12 软件包。
> [add] add MEMS SENSOR: lis2dh12 package.

- peripherals/Kconfig
- peripherals/rda58xx/Kconfig
- peripherals/rda58xx/package.json
RDA5820 SINGLE-CHIP BROADCAST FM TRANSCEIVER
> add peripherals/rda58xx

- peripherals/kendryte-sdk/Kconfig
- peripherals/kendryte-sdk/package.json
windows 本地已经通过测试，menuconfig 成功拉取v0.5.6 且scons编译成功
> upgrade k210 v0.5.6

- peripherals/kendryte-sdk/Kconfig
> move default version v0.5.5 to v0.5.6

- system/LittlevGL2RTT/package.json
[Update] LVGL 0.0.1 package index
> [Update] LVGL 0.0.1 package index

- iot/Kconfig
- iot/rapidjson/Kconfig
- iot/rapidjson/package.json
增加 rapidjson 软件包和9个例程：
- simple_reader: simple reader example
- simple_writer: simple writer example
- tutorial: tutorial example
- simple_pull_reader: simple pull reader example
- simple_dom: simple dom example
- serialize: serialize example
- message_reader: message reader example
- look_ahead_parser: look ahead parser example
- archiver_test: archiver test example
> [iot][rapidjson] new package rapidjson

- iot/protobuf-c/Kconfig
> [iot][protobuf-c] fix typo

- iot/rapidjson/package.json
- misc/cowsay/package.json
- misc/mcurses/package.json
- misc/ukal/package.json
- misc/vt100/package.json
- peripherals/ad7746/package.json
- peripherals/rplidar/package.json
- tools/anv_bench/package.json
- tools/anv_testsuit/package.json
- tools/anv_trace/package.json
- tools/lwlog/package.json
在以前软件包 pkgs --wizard 默认生成的 keyword 上增加了详细分类
> Add keywords

- ai/quest/Kconfig
- ai/quest/package.json
量子计算机模拟器 (QuEST) 之前 package.json 用 pkgs --wizard 生成没有 AI 分类，放在 IoT 忘记改了
> [ai][quest] move from iot to ai

- iot/EmbeddedProto/Kconfig
- iot/EmbeddedProto/package.json
- iot/Kconfig
针对 Cortex-M 优化的 protobuf：
```
msh >encode_decode
---- Encoding ---
a=20, b=10
Encoding 8 serialized bytes
---- Decoding ---
a=20, b=10
msh >
```
> [iot][EmbeddedProto] new package EmbeddedProto

- ai/Kconfig
- ai/naxos/Kconfig
- ai/naxos/package.json
AI Constraint Programming Library
可以解决 nqueens，send_more_money，TSP 问题：
```
msh >nqueens
[[0] [2] [4] [1] [3]]
[[0] [3] [1] [4] [2]]
[[1] [3] [0] [2] [4]]
[[1] [4] [2] [0] [3]]
[[2] [4] [1] [3] [0]]
[[2] [0] [3] [1] [4]]
[[3] [0] [2] [4] [1]]
[[3] [1] [4] [2] [0]]
[[4] [1] [3] [0] [2]]
[[4] [2] [0] [3] [1]]
msh >
```
```
msh >send_more_money
9567
+  1085
= 10652
msh >
```
> [ai][naxos] new package naxos

- ai/elapack/Kconfig
- ai/elapack/package.json
- ai/ulapack/Kconfig
- ai/ulapack/package.json
之前软件包从 misc 移动到了 ai，但是 Kconfig 和 package.json 里面类别，路径忘记改了
> [ai][lapack] fix category

- ai/elapack/package.json
- ai/libann/package.json
- ai/onnx-parser/package.json
- ai/ulapack/package.json
- iot/protobuf-c/package.json
- misc/ukal/package.json
- misc/vt100/package.json
- peripherals/ad7746/package.json
- peripherals/i2c-tools/package.json
- peripherals/rosserial/package.json
- peripherals/rplidar/package.json
- peripherals/u8g2/package.json
- tools/CoreMark/package.json
- tools/Dhrystone/package.json
> [fix] email: wuhanstudio@hust.edu.cn --> wuhanstudio@qq.com

- tools/Kconfig
- tools/devmem/Kconfig
- tools/devmem/package.json
> [add] 添加devmem软件包索引

- peripherals/nes/package.json
- tools/gbk2utf8/package.json
> 更改nes及gbk2utf8软件包地址

- iot/librws/Kconfig
Signed-off-by: WillianChan <chentingwei@rt-thread.com>
> 【添加】librws 软件包相关配置索引

- iot/librws/Kconfig
Signed-off-by: WillianChan <chentingwei@rt-thread.com>
> 【添加】select PKG_USING_MBEDTLS 依赖

- misc/vi/Kconfig
> [vi]增加VI_ENABLE_VERBOSE_STATUS功能

- peripherals/sensors/lsm6dsm/package.json
> 源码仓库迁移到github

- peripherals/Kconfig
- peripherals/tca9534/Kconfig
- peripherals/tca9534/package.json
> add tca9534 package

- multimedia/Kconfig
- multimedia/NUemWin/Kconfig
- multimedia/NUemWin/package.json
> Add NUemWin package linking.

- iot/netutils/Kconfig
- iot/netutils/package.json
https://github.com/RT-Thread/rt-thread/pull/4669
> [NTP]更新Kconfig，将NTP在RTTmaster的配置放入软件包中

- iot/netutils/Kconfig
v1.3.0NTP功能刚刚已经测试通过，可以供用户使用，遂提升默认版本
> 更改netutils默认版本为v1.3.0

- iot/netutils/Kconfig
https://github.com/RT-Thread-packages/netutils/pull/63
> [NTP]增加NTP_USING_AUTO_SYNC功能

- tools/SEGGER_RTT/Kconfig
- tools/SEGGER_RTT/package.json
> [tool] segger_rtt release version

- peripherals/Kconfig
- peripherals/kobuki/Kconfig
- peripherals/kobuki/package.json
ROS Tutrlebot 2 底盘 Kobuki 机器人驱动：
> [peripherals][kobuki] new package kobuki

- multimedia/Kconfig
- multimedia/mp3player/Kconfig
- multimedia/mp3player/package.json
a simple mp3 format music player for rt-thread
> add mp3 player

- peripherals/rosserial/Kconfig
- peripherals/rosserial/package.json
> [peripherals][rosserial] add noetic support

- peripherals/micro_ros/Kconfig
- peripherals/rosserial/Kconfig
> [peripherals][rosserial] add kobuki example

- iot/Kconfig
- iot/rt-link_hw/Kconfig
- iot/rt-link_hw/package.json
> [add] 添加 rt-link_hw 软件包索引文件

- system/Arm-2D/Kconfig
- system/Arm-2D/package.json
- system/Kconfig
> add arm 2d packages index

- language/Kconfig
- language/pikascript/Kconfig
- language/pikascript/package.json
> add pikascript and add kconfig in language

- misc/Controller/Kconfig
- misc/Controller/package.json
增加控制算法包：
- PI:  比例积分控制器
- PR: 比例谐振控制器
- RC: 重复控制器
> add: Controller

- peripherals/micro_ros/Kconfig
开发者大会前一天跑一跑 micro_ros，竟然发现会报错，忘了定义 galactic
> [peripherals][micro_ros] add entry for galactic

- iot/Kconfig
- iot/btstack/Kconfig
- iot/hm/Kconfig
- iot/hm/package.json
添加了 HM (HCI Middleware) 软件包，并添加了 BTStack 对 HM 的支持。
> Add HM package

- iot/Kconfig
- iot/lora_pkt_fwd/Kconfig
- iot/lora_pkt_fwd/package.json
- iot/lora_pkt_sniffer/Kconfig
- iot/lora_pkt_sniffer/package.json
- peripherals/Kconfig
- peripherals/lora_gw_driver_lib/Kconfig
- peripherals/lora_gw_driver_lib/package.json
- peripherals/lora_radio_driver/Kconfig
- peripherals/lora_radio_driver/package.json
add,lora-gw-driver software package
add,lora-pkt-sniffer software package
add,lora-pkt-fwd software package
> add lora-gw-driver ,lora-pkt-sniffer,lora-pkt-fwd software package 

- multimedia/Kconfig
- multimedia/ugui/Kconfig
- multimedia/ugui/package.json
> 【添加】 ugui软件包

- peripherals/Kconfig
- peripherals/bouffalolab_sdk/Kconfig
- peripherals/bouffalolab_sdk/package.json
> [add] bouffalolab mcu sdk

- tools/uMCN/Kconfig
- tools/uMCN/package.json
Add option to enable example and command
> Update uMCN package

- peripherals/sensors/Kconfig
- peripherals/sensors/fingerprint/Kconfig
- peripherals/sensors/fingerprint/package.json
add fingerprint module driver packages
> add fingerprint module driver packages

- iot/Kconfig
- iot/small_modbus/Kconfig
- iot/small_modbus/package.json
> add small modbus packages

- language/pikascript/Kconfig
- language/pikascript/package.json
> Add pikascript v1.2.0

- system/TinyUSB/Kconfig
> [tinyusb] Update Kconfig

- language/pikascript/Kconfig
- language/pikascript/package.json
update pikascript pacakge info and url
> update pikascript pacakge info and url

- system/Kconfig
- system/usb_stack/Kconfig
- system/usb_stack/package.json
How to use this package，you can click this link: [RT-Thread package Userguide](https://github.com/sakumisu/usb_stack/blob/master/docs/rt-thread.md)
> add usb stack package support

- system/usb_stack/Kconfig
- system/usb_stack/package.json
- fix package category
- add usb high in full speed for snopsys usb otg ip
> [usb_stack] add hs in full mode

- iot/NimBLE/Kconfig
use the nimble v1.0.0 to default. The latest for debug version
> [nimble]Update Kconfig 

- misc/Kconfig
- misc/design_pattern/Kconfig
- misc/design_pattern/package.json
> add design pattern package

- peripherals/sensors/mmc3680kj/Kconfig
- peripherals/sensors/mmc3680kj/package.json
添加美新(MEMSIC)公司的一款磁力计(mmc3680kj)驱动
>  add a sensor driver of mmc3680kj

- system/Kconfig
- system/LuatOS_SOC/Kconfig
- system/LuatOS_SOC/package.json
add:LuatOS-SOC packages 
LuatOS : https://gitee.com/openLuat/LuatOS
> add:LuatOS-SOC packages

- system/LuatOS_SOC/Kconfig
> add:添加软件定时依赖，luatos_timer需要对接

- iot/iot_cloud/Kconfig
- iot/iot_cloud/ez_iot_os/Kconfig
- iot/iot_cloud/ez_iot_os/components/FlashDB/Kconfig
- iot/iot_cloud/ez_iot_os/components/cJSON/Kconfig
- iot/iot_cloud/ez_iot_os/components/ezconn/Kconfig
- iot/iot_cloud/ez_iot_os/components/ezlist/Kconfig
- iot/iot_cloud/ez_iot_os/components/ezlog/Kconfig
- iot/iot_cloud/ez_iot_os/components/eztimer/Kconfig
- iot/iot_cloud/ez_iot_os/components/ezutil/Kconfig
- iot/iot_cloud/ez_iot_os/components/ezutil/misc/Kconfig
- iot/iot_cloud/ez_iot_os/components/ezutil/s2j/Kconfig
- iot/iot_cloud/ez_iot_os/components/ezutil/uuid/Kconfig
- iot/iot_cloud/ez_iot_os/components/ezxml/Kconfig
- iot/iot_cloud/ez_iot_os/components/http_server/Kconfig
- iot/iot_cloud/ez_iot_os/components/mbedtls/Kconfig
- iot/iot_cloud/ez_iot_os/components/mqtt/Kconfig
- iot/iot_cloud/ez_iot_os/components/utest/Kconfig
- iot/iot_cloud/ez_iot_os/components/webclient/Kconfig
- iot/iot_cloud/ez_iot_os/examples/Kconfig
- iot/iot_cloud/ez_iot_os/eziot/ez_iot_bm/Kconfig
- iot/iot_cloud/ez_iot_os/eziot/ez_iot_bm/base/Kconfig
- iot/iot_cloud/ez_iot_os/eziot/ez_iot_bm/hub/Kconfig
- iot/iot_cloud/ez_iot_os/eziot/ez_iot_bm/model/Kconfig
- iot/iot_cloud/ez_iot_os/eziot/ez_iot_bm/ota/Kconfig
- iot/iot_cloud/ez_iot_os/eziot/ez_iot_bm/shadow/Kconfig
- iot/iot_cloud/ez_iot_os/eziot/ez_iot_bm/tsl/Kconfig
- iot/iot_cloud/ez_iot_os/eziot/ez_iot_core/Kconfig
- iot/iot_cloud/ez_iot_os/package.json
- iot/iot_cloud/ez_iot_os/platform/bsp/rt-thread/Kconfig
- iot/iot_cloud/ez_iot_os/unit_test/Kconfig
- 适配RT-Thread软件包
- 支持设备接入、在线升级、萤石物模型协议、子设备管理等
> 增加萤石IoT软件包索引

- peripherals/bluetrum_sdk/Kconfig
- peripherals/bluetrum_sdk/package.json
原先的 v0.0.3 版本有问题，更新一下 v0.0.3 的链接
> [bluetrum] fix v0.0.3

- tools/SEGGER_RTT/Kconfig
- tools/SEGGER_RTT/package.json
> [tools/segger_rtt] update the config

- peripherals/touch/Kconfig
- peripherals/touch/xpt2046/Kconfig
- peripherals/touch/xpt2046/package.json
> adding xpt2046 driver package

- iot/at_device/Kconfig
Delete unnecessary dependency (AT_USING_SOCKET)
https://github.com/RT-Thread/packages/issues/1167
> Delete unnecessary dependency (AT_USING_SOCKET)

- system/lwext4/package.json
> [lwext4] 转让到RT-Thread-packages组织

- system/syswatch/Kconfig
- system/syswatch/package.json
> release syswatch v1.0.1

- misc/Kconfig
- misc/MFBD/Kconfig
- misc/MFBD/package.json
add multi-function button detection package.
> add mfbd package

- peripherals/sensors/Kconfig
- peripherals/sensors/qmp6989/Kconfig
- peripherals/sensors/qmp6989/package.json
> add qmp6989 sensor driver package

- system/Kconfig
- system/kmulti_rtimer/Kconfig
- system/kmulti_rtimer/package.json
> release kmulti_rtimer

- misc/MFBD/Kconfig
- misc/MFBD/package.json
[UPDATE] MFBD update to v1.0.1. Each mbtn has it's own max multi-click times.
> [UPDATE] MFBD update to v1.0.1

- system/CherryUSB/Kconfig
- device 和 host 选项分开
- device 的 config 进行重构
-  增加 template 的控制
> [CherryUSB] add usb host mode,refactor device config

- system/Kconfig
- system/TFDB/Kconfig
- system/TFDB/package.json
[ADD]add tiny flash database Library package for rt thread.
> [ADD]add tiny flash database Library.

- tools/Kconfig
- tools/hash-match/Kconfig
- tools/hash-match/package.json
[ADD]add hash-match package for rt thread.
> [ADD]add hash-match package.

- multimedia/LVGL/LVGL/Kconfig
related: https://github.com/lvgl/lvgl/pull/3355
> improve lvgl marcos

- language/Kconfig
- language/rtt_rust/Kconfig
- language/rtt_rust/package.json
Signed-off-by: vitors <260437028@qq.com>
> [rtt_rust]: add package rtt_rust.

- iot/Kconfig
- iot/zFTP/Kconfig
- iot/zFTP/package.json
add a zFTP client package to rt-thread package
> add a zFTP client package

- peripherals/touch/gt9147/Kconfig
- peripherals/touch/gt9147/package.json
> add gt9147 v1.0.0、v1.1.0

- system/CMSIS/CMSIS_5/Kconfig
ARM那边要搞一些猥琐的事情，我刚搞定了CMSIS5的适配，他们就要把DSP拆出去 可恶
> CMSIS默认版本使用发布版本

- multimedia/LVGL/LVGL/Kconfig
- multimedia/LVGL/LVGL/package.json
https://github.com/lvgl/lvgl/issues/3173
> release lvgl v8.3.0

- iot/iot_cloud/onenet/Kconfig
- iot/pahomqtt/Kconfig
summer 夏令营活动中发现的因为版本版本问题造成的编译错误
> avoid unnecessary error about file is lost through version control.

- multimedia/LVGL/LVGL/Kconfig
LVGL side related PR: https://github.com/lvgl/lvgl/pull/3566
> [lvgl] support SquareLine Studio

- system/FreeRTOS_Wrapper/Kconfig
- system/FreeRTOS_Wrapper/package.json
> FreeRTOS wrapper: do not automatically select RT_USING_TIMER_SOFT

- arduino/sensors/Adafruit-FXOS8700/Kconfig
- arduino/sensors/Adafruit-FXOS8700/package.json
- arduino/sensors/Kconfig
[arduino][sensors][Adafruit-FXOS8700] 添加FXOS8700传感器软件包
> [arduino][sensors][Adafruit-FXOS8700]

- arduino/sensors/Adafruit-HMC5883-Unified/Kconfig
- arduino/sensors/Adafruit-HMC5883-Unified/package.json
- arduino/sensors/Kconfig
[arduino][sensors][Adafruit-HMC5883-Unified] 添加HMC5883传感器软件包
> [arduino][sensors][Adafruit-HMC5883-Unified]

- arduino/sensors/Adafruit-HDC1000/Kconfig
- arduino/sensors/Adafruit-HDC1000/package.json
- arduino/sensors/Kconfig
[arduino][sensors][Adafruit-HDC1000] 添加HDC1000传感器
> [arduino][sensors][Adafruit-HDC1000]

- arduino/sensors/Adafruit-HTU21DF/Kconfig
- arduino/sensors/Adafruit-HTU21DF/package.json
- arduino/sensors/Kconfig
[arduino][sensors][Adafruit-HTU21DF] 添加HTU21DF传感器软件包
> [arduino][sensors][Adafruit-HTU21DF]

- arduino/sensors/Adafruit-HTU31D/Kconfig
- arduino/sensors/Adafruit-HTU31D/package.json
- arduino/sensors/Kconfig
[arduino][sensors][Adafruit-HTU31D] 添加HTU31D传感器软件包
> [arduino][sensors][Adafruit-HTU31D]

- arduino/sensors/Adafruit-INA260/Kconfig
- arduino/sensors/Adafruit-INA260/package.json
- arduino/sensors/Kconfig
[arduino][sensors][Adafruit-INA260] 添加INA260传感器软件包
> [arduino][sensors][Adafruit-INA260]

- arduino/sensors/Adafruit-L3GD20/Kconfig
- arduino/sensors/Adafruit-L3GD20/package.json
- arduino/sensors/Kconfig
[arduino][sensors][Adafruit-L3GD20] 添加L3GD20传感器软件包
> [arduino][sensors][Adafruit-L3GD20]

- iot/Kconfig
- iot/RyanMqtt/Kconfig
- iot/RyanMqtt/package.json
> add RyanMqtt package

- misc/MFBD/Kconfig
- misc/MFBD/package.json
> [UPDATE]MFBD update to v1.0.3

- peripherals/sensors/Kconfig
- peripherals/sensors/sths34pf80/Kconfig
- peripherals/sensors/sths34pf80/package.json
> add sensor sths34pf80 support 

- .github/workflows/action.yml
拆分 test 流程
指定 ci test 时 scons 版本
修复没有修改索引文件时，ci test 报错的问题
> 修复 因 scons 版本导致的 scons 编译问题

- tools/Kconfig
- tools/RT_Trace/Kconfig
- tools/RT_Trace/package.json
> 【更新】添加 RT_Trace 软件包

- peripherals/aip650/Kconfig
add AIP650_TEST_KEY in example
> add macro AIP650_TEST_KEY.

- peripherals/Kconfig
- peripherals/spi-tools/Kconfig
- peripherals/spi-tools/package.json
> add spi-tools.

- misc/lzma/package.json
- peripherals/sensors/as7341/package.json
- peripherals/touch/gt911/package.json
Due to the old github account no longer being used, the contributed software packages will be migrated to the new account
> modify Repository to new repository

- peripherals/Kconfig
- peripherals/bt_ecb02c/Kconfig
- peripherals/bt_ecb02c/package.json
> add bt_ecb02c

- misc/optparse/Kconfig
- misc/optparse/package.json
> [optparse] 新增 v1.0.0版本

- peripherals/Kconfig
- peripherals/st7789/Kconfig
- peripherals/st7789/package.json
> add st7789 spi lcd graphic driver.

- security/mbedtls/Kconfig
- security/mbedtls/package.json
Mbedtls add a release version v2.7.10.2
> update mbedtls packages

- system/FreeRTOS_Wrapper/Kconfig
add PKG_FREERTOS_USING_PRELOAD_CONFIG
add PKG_FREERTOS_USING_MEMMANG
> [FreeRTOS] add PKG_FREERTOS_USING_PRELOAD_CONFIG

- peripherals/io_input_filter/Kconfig
- peripherals/io_input_filter/package.json
IO输入软件滤波模块升级至2.0.0，API更新，更加方便使用
> 更新软件滤波模块API，使其更加方便易用

- tools/Kconfig
- tools/zdebug/Kconfig
- tools/zdebug/package.json
方便的调试工具，随时控制打印 log，查看、设置变量数据，执行函数。
> Add zdebug package

- iot/zephyr_polling/Kconfig
zephyr_polling add chipset  BLUENRG2
HCI use SPI
> feat: (zephyr_polling) chipset BLUENRG2, HCI using SPI

- peripherals/Kconfig
- peripherals/vs1003/Kconfig
- peripherals/vs1003/package.json
> add vs1003 driver

- signalprocess/CMSIS-DSP/Kconfig
针对CMSIS-DSP，增加了对应的编译Kconfig控制，需要管理同时将RT-thread package下的CMSIS-DSP仓库的Pull Request同时处理一下
> improve CMSIS-DSP package

- system/Kconfig
- system/rtp/Kconfig
- system/rtp/package.json
Add cross platform thread pool(RTP) components
> Add cross platform thread pool(RTP) components

- peripherals/Kconfig
- peripherals/x9555/Kconfig
- peripherals/x9555/package.json
First submission of x9555 package.
> Add x9555 device

- misc/MFBD/Kconfig
- misc/MFBD/package.json
> [UPDATE]MFBD update to v1.0.5.

- peripherals/x9555/Kconfig
Reverts RT-Thread/packages#1692
> Revert "Add x9555 device"

- iot/kawaii-mqtt/Kconfig
用户可以直接在menuconfig对Demo程序的一些重要参数进行配置。
https://github.com/jiejieTop/kawaii-mqtt/pull/13
> [iot][kawaii-mqtt] Demo程序宏定义支持

- tools/Micro-XRCE-DDS-Client/Kconfig
> [fix] 添加sys/select依赖项

- system/TinyUSB/Kconfig
prepare TinyUSB/Host parameters
> add TinyUSB Host parameters

- iot/wifi-host-driver/Kconfig
- iot/wifi-host-driver/package.json
add support for pin names
add support for custom nvram files
deleted the v1.0.0 version
> update wifi host drivers

- signalprocess/CMSIS-DSP/Kconfig
> [CMSIS-DSP] update Kconfig

- peripherals/sensors/sgp30/Kconfig
> [sensor_v1]adapt for sgp30

- iot/wiznet/Kconfig
> fix wiznet build

- .github/workflows/aciont_tool.yml
https://github.com/RT-Thread/packages/actions/runs/13087460815
添加menuconfig检查
https://github.com/RT-Thread/packages/issues/1851
> [ci] trigger menuconfig check

- system/littlefs/Kconfig
add RT_DEF_LFS_DRIVERS config, to make multi lfs partition enable.
> Update lfs Kconfig

- misc/samples/network_samples/Kconfig
select RT_USING_POSIX_FS
select RT_USING_POSIX_SOCKET
> [misc/samples/network_samples] add select for tcp client by select api.

- iot/iot_cloud/onenet/Kconfig
- iot/iot_cloud/onenet/package.json
@Rbb666 @supperthomas 麻烦帮忙合并一下~
> Update the index of the Onenet software package

- peripherals/sensors/Kconfig
- peripherals/sensors/qmi8658/Kconfig
- peripherals/sensors/qmi8658/package.json
添加qmi8658a传感器IMU软件包,支持三轴加速度计与三轴角速度的读取
> add qmi8658 sensor

- tools/SystemView/Kconfig
该软件包依赖RT_USING_HOOKLIST 配置，添加该宏
> [sysview] 添加RT_USING_HOOKLIST

- iot/FreeMQTT/Kconfig
- iot/FreeMQTT/package.json
- iot/Kconfig
> 添加FreeMQTT软件包
