RT-Thread/packages

- iot/pahomqtt/Kconfig
1.修复更新导致包无法下载问题（tab对齐）
2.设置latest_version为默认下载版本
> update paho mqtt index

- system/minIni/Kconfig
- system/minIni/package.json
Add minIni library for rt-thread. minIni is a portable and configurable library for reading and writing ".INI" files.
> add minIni

- multimedia/Kconfig
- multimedia/mupdf/Kconfig
- multimedia/mupdf/package.json
Add mupdf package to multimedia. Currently, this work is based on an old version of mupdf v1.2.0.
> Add mupdf package to multimedia.

- misc/Kconfig
- misc/optparse/Kconfig
- misc/optparse/package.json
optparse是一个开源, 可移植的, 可重入的和可嵌入的类getopt命令行参数解析器. 它支持POSIX getopt选项字符串, GNU风格的长参数解析, 参数置换和子命令处理.
> [add] add optparse(getopt-like) pkg support. | 添加optparse(类getopt)包支持.

- peripherals/Kconfig
- peripherals/u8g2/Kconfig
- peripherals/u8g2/package.json
u8g2 是一个液晶显示屏驱动，支持非常多的液晶屏:
SSD1305, SSD1306, SSD1309, SSD1322, SSD1325, SSD1327, SSD1329, SSD1606, SSD1607, SH1106, 
SH1107, SH1108, SH1122, T6963, RA8835, LC7981, PCD8544, PCF8812, HX1230, UC1601, UC1604,  
UC1608, UC1610, UC1611, UC1701, ST7565, ST7567, ST7588, ST75256, NT7534, IST3020, ST7920, 
LD7032, KS0108, SED1520, SBN1661, IL3820, MAX7219 ...
原始项目地址: 
> [https://github.com/olikraus/u8g2](https://github.com/olikraus/u8g2)
ARM Linux 移植: 
> [https://github.com/wuhanstudio/u8g2-arm-linux](https://github.com/olikraus/u8g2)
在征得原作者 [许可](https://github.com/olikraus/u8g2/issues/711) 的情况下，我在尝试把它移植到不同平台，在 rt-thread 上的 [I2C 液晶屏](https://github.com/wuhanstudio/rt-u8g2/tree/master/examples) 已经能正常工作了，之后也会支持 SPI 和 GPIO.
> Add u8g2 library, a library for monochrome displays

- peripherals/Kconfig
- peripherals/button/Kconfig
- peripherals/button/package.json
纯C语言实现的一个按键驱动，可移植性强，支持单双击、连按、连按释放、长按；采用回调处理按键事件（自定义消抖时间），使用只需3步，1：创建按键，2：按键事件与回调处理函数链接映射。然后周期检查按键。
> 更新外设-按键驱动，已经测试完成，

- misc/CanFestival/Kconfig
* auto select RT_USING_CAN and RT_USING_HWTIMER, because CanFestival depends on these drivers.
* move CanFestival options to upper menu, there's no need to have such deep menu.
> [CanFestival] auto select RT_USING_CAN and RT_USING_HWTIMER

- iot/netutils/package.json
- 增加 分类信息（必选），与 env 中菜单类别对应
- 增加 作者信息（必选），包括名字及邮箱
- 增加 许可信息（必选）
- 增加 仓库信息（可选），暂时使用 GitHub 地址
- 增加 图标信息（可选）
- 增加 首页信息（可选），指向用户的软件包首页（可定制非 GitHub 地址）
- 增加 文档信息（可选）
先确定这一个软件包的改法，确认后批量修改其他软件包
> 【完善】软件包索引信息内容。

- iot/iot_cloud/tencent-iotkit/Kconfig
package 腾讯云 kconfig文件有语法错误，使用menuconfig的时候会有警告信息，如下图所示：
> [packages]fix kconfig file syntax error

- peripherals/sensors/lsm303agr/Kconfig
[peripherals/sensors][lsm303agr] 修复双引号不成对的错误
> [peripherals/sensors][lsm303agr] 修复双引号不成对的错误

- peripherals/Kconfig
- peripherals/sx12xx/Kconfig
- peripherals/sx12xx/package.json
增加sx12xx 驱动 软件包支持,适用外设Semtech sx12xx LoRa chip
> add sx12xx Semtech LoRa RF chip driver library

- peripherals/Kconfig
- peripherals/infrared/Kconfig
- peripherals/infrared/package.json
基于  rt-thread `pin` 、 `pwm` 、 `hwtimer` 的红外驱动。
1. 在正点原子 L4 IoT board 测试通过。
2. 在正点原子 F407 测试通过。
> [add] infrared drive framework

- peripherals/Kconfig
- peripherals/rosserial/Kconfig
- peripherals/rosserial/package.json
rosserial 是机器人操作系统(ROS)的一个通讯协议，最近把它移植到了 rt-thread 。
[ROS ](http://www.ros.org/)(Robots Operating System) 最早是斯坦福大学的一个软件框架，现在不管是工业机器人，还是娱乐用的机器人都运行着ROS。为了保证稳定性，机器人通常是由不同节点组成的，节点间的通信就是靠 rosserial 协议实现的。
rt-thread 支持的处理器非常多，把 rosserial 移植到 rt-thread后，希望今后机器人节点说不定就是 ROS + RT-Thread 搭配了。大量高性能计算用主节点 Ubuntu 跑 ROS，外设节点用 RT-Thread 采集传感器数据，感觉这样搭配还是挺不错的 ;)
> [new package] rosserial

- peripherals/u8g2/Kconfig
- peripherals/u8g2/package.json
- 之前也是把 I2C 和 SPI 的总线写死在代码里了，所以把他们分离了出来
- 发布了 v1.2.0
> [u8g2] Get device name from Kconfig

- peripherals/Kconfig
- peripherals/bh1750/Kconfig
- peripherals/bh1750/package.json
Hi， 我添加了BH1750FVI数字光照强度传感器IC的驱动软件包，已经测试通，软件包放在我的GitHub：https://github.com/sanjaywu/bh1750，请审核，有如问题请指出指正，我完善修改，谢谢！
> 增加BH1750FVI传感器驱动软件包

- system/gui_engine/Kconfig
compile error: 'GUIENGINE_NAME_MAX' undeclared here (not in a function)
> fix：compile error: 'GUIENGINE_NAME_MAX' undeclared here

- security/mbedtls/Kconfig
- security/mbedtls/package.json
增加了一些配置
- 密钥长度。针对仅支持 128 位硬件加解密的芯片
- 大数最大长度。
增加 2.7.10 版本
> 【更新】mbedtls 软件包索引

- misc/Kconfig
- misc/libann/Kconfig
- misc/libann/package.json
添加轻量级的 ANN 软件包，可以在 stm32 上训练 ANN 模型。
以经典的 Iris 数据集为例，使用一层隐藏层、隐藏层节点为4，训练 150 个样本，迭代 500 次，在 STM32L475VET6 上训练时间为 24 秒，预测时间为 22 毫秒，预测精度为 96.0%。
> Upstream libann

- peripherals/i2c_tools/Kconfig
软件包路径不小心写成了大写，windows 不区分大小写一直没发现
> [i2c-tools] Use lowercase

- iot/onnx-parser/Kconfig
- 软件包默认选中 libc：文件操作从 rt-thread api 切为 POSIX C
- 添加解析 C 数组模型的例子：xxd -i mnist.onnx > mnist_onnx.c
> Upstream onnx add example

- iot/Kconfig
- iot/onnx-backend/Kconfig
- iot/onnx-backend/package.json
在 RT-Thread 上解析通用机器学习 onnx 模型，这样就可以在 RT-Thread 上运行几乎所有主流机器学习框架了。
- Tensorflow
- Keras
- Pytorch
- Caffe2
- mxnet 
- 等等
现在成功加载 Keras 的模型并在 STM32F407 上面进行手写体识别。
```
msh />onnx_mnist 1
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@        @@@@@@@@@@@@@@@@@@
@@@@@@@@@@@@@@@@@@@@@@@@@@              @@@@@@@@@@@@@@@@
@@@@@@@@@@@@@@@@@@@@@@                    @@@@@@@@@@@@@@
@@@@@@@@@@@@@@@@@@@@          @@@@@@@@    @@@@@@@@@@@@@@
@@@@@@@@@@@@@@@@@@@@        @@@@@@@@@@    @@@@@@@@@@@@@@
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@  @@@@@@ …
```
> [new][iot] Add package onnx-backend

- misc/Kconfig
- misc/vt100/Kconfig
- misc/vt100/package.json
RT-Thread 的终端 msh 一直是一个非常受大家欢迎的组件，但是终端只能打印基本的字符未免有些单调了，于是我封装了 ANSI Escape 标准，这样就可以在 msh 里实现更加丰富的图形界面了，例如动画和游戏开发。
小火车还有不同类型
> [new][misc] Add package vt100

- misc/Kconfig
- misc/ukal/Kconfig
- misc/ukal/package.json
- misc/ulapack/Kconfig
- misc/ulapack/package.json
> LAPACK: linear algebra package 是非常经典的线性代数库。
之前移植的 elapack 是从最早的 Fortran 转换成的 C 版本，并且提供了和 Matlab 兼容的接口，功能非常全，但是从 Fortran 转换过来很多数组是静态声明的，如果矩阵维度太大，一不小心就容易 stackoverflow，适合 Flash 非常大，内存也相对比较丰富的板子。
这个 ulapack 则是原生 C 实现的，矩阵的内存动态分配，更加轻量级，但是功能也就不是那么丰富，不过也包含了主流的矩阵运算，适合 Flash 比较小，内存也紧缺的板子。考虑到有些板子内存小到无法使用 heap，之后还是要在 KConfig 里增加静态、动态分配的选项。
包含例程：
- 矩阵 LU 分解
- 矩阵 SVD 分解
- 主成分分析 PCA
- 多项式拟合
> 两个软件包相互依赖，就放在一个 PR 里面了
----------------------
基于 ulapack 的卡尔曼滤波器。
包含例程:
- Extended kalman filter
-----------------------------------
- 为 ulapack 增加了 内存动态/静态分配 选项
- 为 ukal 增加了 内存动态/静态分配 提示
- 增加静态分配内存时矩阵最大维度配置
elapck (静态分配):
| Example | Memory |
|----------|-------------|
| linsolve 线性方程组 |  2 KB |
| qr 矩阵 QR 分解 |  2 KB |
| lu 矩阵 LU 分解 |  2 KB |
| svd 矩阵 SVD 分解 |  20 KB |
| eig 特征值和特征向量 | 30 KB |
| model 综合控制模型预测 …
> [misc][ulapack] new package ulapack

- peripherals/rosserial/Kconfig
- peripherals/rosserial/package.json
ROS 的 Kinetic (Ubuntu 16) 和 Melodic (Ubuntu 18) 现在都用的比较多，因此开了 kinetic-latest 和 melodic-latest 分别维护，适配不同的 ROS 版本，之前还沒意识到 package.json 指定的 master 是分支名
> [peripherals][rosserial] Distinguish kinetic & melodic

- peripherals/u8g2/Kconfig
- peripherals/u8g2/package.json
有人发邮件给我希望用纯 C 版本的 u8g2，避免 C/C++ 混合编译，于是把 C/C++ 分成两个分支分别维护
> [peripherals][u8g2] Distinguish C and C++

- tools/CoreMark/Kconfig
- tools/CoreMark/package.json
- tools/Kconfig
增加 CoreMark 软件包， MCU/CPU 性能测试小工具。
```
\ | /
/ | \     4.0.2 build Oct 13 2019
2006 - 2019 Copyright by rt-thread team
msh >
msh >core_mark
Benchmark started, please make sure it runs for at least 10s.
2K performance run parameters for coremark.
CoreMark Size    : 666
Total ticks      : 17776
Total time (secs): 17.776000
Iterations/Sec   : 135.013501
Iterations       : 2400
Compiler version : Please put compiler version here (e.g. gcc 4.1)
Compiler flags   :
Memory location  : STACK
seedcrc          : 0xe9f5
[0]crclist       : 0xe714
[0]crcmatrix     : 0x1fd7
[0]crcstate      : 0x8e3a
[0]crcfinal      : 0x382f
Correct operation validated. See README.md for run and reporting rules.
CoreMark 1.0 : 135.013501 / Please put compiler version here (e.g. gcc 4.1) …
```
> [tools][coremark] new package coremark

- tools/CoreMark/Kconfig
- tools/Kconfig
- tools/dhrystone/Kconfig
- tools/dhrystone/package.json
历史悠久的 dhrystone 性能测试小工具：
```
\ | /
/ | \     4.0.2 build Oct 15 2019
2006 - 2019 Copyright by rt-thread team
msh >
msh >dhrystone_test
Dhrystone Benchmark, Version 2.1 (Language: C)
Program compiled without 'register' attribute
Execution starts, 320000 runs through Dhrystone
Execution ends
Final values of the variables used in the benchmark:
Int_Glob:            5
should be:   5
Bool_Glob:           1
should be:   1
Ch_1_Glob:           A
should be:   A
Ch_2_Glob:           B
should be:   B
Arr_1_Glob[8]:       7
should be:   7
Arr_2_Glob[8][7]:    320010
should be:   Number_Of_Runs + 10
Ptr_Glob->
Ptr_Comp:          536892000
should be:   (implementation-dependent)
Discr:             0
should be:   0
Enum_Comp:         2
should be:   2
Int_Comp: …
```
> [tools][dhrystone] New package dhrystone

- tools/Kconfig
将 ../nr_micro_shell/Kconfig 路径添加到 ../tools/Kconfig  文件中，使 ENV 工具能够识别下载nr_micro_shell package。
> add nr_micro_shell to Kconfig in tools.

- security/Kconfig
- security/trusted-firmware-m/Kconfig
- security/trusted-firmware-m/package.json
TFM is an implementation of SPE which compliant with PSA. Add TFM as a
package of RTT, it is the first step to get PSA certified for RTT.
Currently, TFM official repo does not support LPC55S69 board. We are waiting for the TFM contributor who is working on the LPC board enablement. This PR will make TFM package available in RTT menuconfig, and will update TFM package when LPC55S69 has merged into TFM repo.
Signed-off-by: Karl Zhang <karl.zhang@arm.com>
> TFM: Add Trusted firmware for M as package

- security/trusted-firmware-m/package.json
TFM package for LPC55S69 got first relase.
Signed-off-by: Karl Zhang <karl.zhang@arm.com>
> TFM Package: Update to TFM pacakage URL

- security/trusted-firmware-m/Kconfig
- security/trusted-firmware-m/package.json
LPC board now is not offically supported by TFM, we release a legacy LPC
support version with TFM 1.0 beta.
This change will add the version name into menuconfig for easier to
read.
Signed-off-by: Karl Zhang <karl.zhang@arm.com>
> TFM: clear the version name for LPC

- multimedia/mupdf/package.json
- peripherals/sensors/aht10/package.json
- peripherals/sensors/ap3216c/package.json
- peripherals/sensors/dht11/package.json
- peripherals/sht2x/package.json
- system/minIni/package.json
- system/rti/package.json
在拉取一些软件包时，提示 error: pathspec 'mater' did not match any file(s) known to git. 经检查后将部分软件包的 latest 版本的 VER_SHA 值由 mater 修改为 master。
> fixed typos: mater -> master

- peripherals/Kconfig
- peripherals/embARC_bsp/Kconfig
- peripherals/embARC_bsp/package.json
Add synopsys embARC_bsp support as a system package.
The embARC Board support Package (BSP) is a software distributions
aimed at facilitating the development and evaluation of embedded
systems based on Synopsys ARCv2 processors, which is designed to
provide a minimal board support package for ARC users by defining
consistent and simple software interfaces to the processors
and onboard devices.
Signed-off-by: Watson Zeng <zhiwei@synopsys.com>
> [peripherals][embARC_bsp] add synopsys embARC_bsp support

- peripherals/Kconfig
- peripherals/beep/Kconfig
- peripherals/beep/package.json
- peripherals/easyblink/Kconfig
- peripherals/easyblink/package.json
1、添加了 easyblink 软件包。
小巧轻便的LED控制软件包，可以容易地控制LED开、关、反转和各种间隔闪烁，占用RAM少，可以设置成线程安全型的；不需要移植就可以同时适用 RT-Thread 标准版和 Nano 版。
2、更新了 beep 软件包的信息。
> Add easyblink package

- peripherals/Kconfig
- peripherals/nuclei_sdk/Kconfig
- peripherals/nuclei_sdk/package.json
Package `nuclei-sdk` is only used for supporting Nuclei RISC-V
processor based system, which included SoC peripherals
of different system.
For more information about it, click https://doc.nucleisys.com/nuclei_sdk
Signed-off-by: Huaqi Fang <578567190@qq.com>
> package: Add new peripheral/bsp package nuclei-sdk

- peripherals/nuclei_sdk/Kconfig
Due to ARCH_NUCLEI is not allowed in RT-Thread, so remove ARCH_NUCLEI and use ARCH_RISCV instead, and add comment for using Nuclei SDK to warning people to not use Nuclei SDK package if they are not using Nuclei RISC-V processor.
> nuclei: Modify nuclei_sdk package kconfig

- system/sqlite/Kconfig
更新sqlite Kconfig文件，适配新PR的sqlite软件包，可实现数据库名称，SQL语句长度，是否开启DAO层示例功能，如下：
RT-Thread online packages  ---> 
system packages  ---> 
--- SQLite: a self-contained, high-reliability, embedded, full-featured, public-domain, SQL database engine.
(/rt.db) Database name(path)
(1024) SQL statements max length
[*]   Enable example
> 更新sqlite Kconfig文件，适配新PR的sqlite软件包

- misc/vt100/Kconfig
> [misc][vt100] Add draw img example

- iot/at_device/bc28/Kconfig
- iot/bc28_mqtt/Kconfig
为增加 bc28 at_device 软件包的灵活性，增加了 BC28_SAMPLE_MIN_SOCKET 和 BC28_SAMPLE_BAUD_RATE 两个配置项，分别用于配置模块可用的最小 socket 号和 UART 波特率。
> [at_device] Add configs for bc28 class

- system/Kconfig
- system/ramdisk/Kconfig
- system/ramdisk/package.json
A ramdisk block device can be formatted.
- Replace ROMFS as root dir
- Fast file caching.
- Works like any other block device.
Originally I wanted to dynamically create dir in root dir. But it is not possible when using ROMFS as root. The original RTT RAMFS does not support dir. Thus I wrote this simplified ramdisk based on the block device framework. It works just like a normal block device. 
Very handy when working with SDRAM and formatted to a filesystem.
> Add ramdisk block device

- peripherals/sensors/Kconfig
在查阅sensor软件包代码时发现，目前一共有35个sensor软包，但是Kconfig中只记录了34个。仔细对照，发现漏了RT3020软件包呀。。。难怪 rt3020 软件包的下载量是零 :cry:
> [Sensor] Fill in missing package information (rt3020)

- iot/at_device/m5311/Kconfig
将原本写在socket组件里所需要的缓冲大小代码调整到menuconfig这里，方便用户修改。  
其他：删除不必要空行的空格。
> add send and recv buffer parameters

- peripherals/Kconfig
- peripherals/wk2124/Kconfig
- peripherals/wk2124/package.json
Add a new peripheral driver of wk2124, which is a SPI to serial chip. It helps the chip expand more uart serial ports
> Add the peripheral driver for wk2124

- peripherals/lora_radio_driver/Kconfig
- peripherals/lora_radio_driver/package.json
更新lora-radio-driver\Kconfig 软件包配置文件
- 区分单实例(单lora模块)与多实例（多lora模块）情况，目前支持单实例
- 移除了Kconfig中对BSP_USING_SPIx的直接定义，BSP_USING_SPIx定义调整到[Target Platform]\Board\Kconfig)
- 重命名宏定义REGION_X为PHY_REGION_X(如REGION_CN470 -> PHY_REGION_CN470)，以便与LoRaWAN协议栈中缺省REGION_X共存
> lora-radio v1.1 update

- misc/Kconfig
- misc/TensorflowLiteMicro/Kconfig
- misc/TensorflowLiteMicro/package.json
这是2020暑期开源软件供应链Tensorflow LIte Micro移植到基于rtt内核的树莓派4项目的延伸, 在成功将Tensorflow LIte Micro移植到树莓派4之后, 考虑TFLiteMicro本身具有平台隔离的特性, 所以我尝试将其制作为软件包, 就有了这份PR.
由于时间仓促, 软件包的功能, 文档等诸多方面还都有待完善,  我回持续更新软件包的信息, 使其适用于更多基于RTT内核的硬件, 也请您在百忙之中可以揽阅软件包的情况, 您提出的意见和建议我都会仔细考虑的.
> 增加了Tensorflow Lite Micro软件包索引

- peripherals/u8g2/Kconfig
> [peripherals][u8g2] select cpp dependency

- peripherals/rosserial/Kconfig
> [peripherals][rosserial] select cpp dependency

- misc/TensorflowLiteMicro/package.json
对Tensorflow Lite Micro软件包进行了一次深度矫正, 之前的v1.0.0版本实际是不能正确使用的, 经过此次修正之后的软件包才是真正意义上的v1.0.0, 故提交一个pr
> 更新了tag版本(之前的v1.0.0版本有bug)

- tools/Kconfig
- tools/lwrb2rtt/Kconfig
- tools/lwrb2rtt/package.json
lwrb2rtt 是一个轻量级的环形缓冲区管理软件包，提供了通用的 FIFO 环形缓冲区实现。
此项目完成了开源的 lwrb 与 rt-thread 的匹配。
> add lwrb2rtt packages

- peripherals/i2c-tools/Kconfig
源码用了 C++，默认选中 RT_USING_CPLUSPLUS
> [peripherals][i2c-tolls] select cpp

- misc/zlib/Kconfig
Use `if RT_USING_DFS` for zlib sample in Kconfig.
> Use condition for zlib sample in Kconfig

- peripherals/nuclei_sdk/Kconfig
- peripherals/nuclei_sdk/package.json
Nuclei SDK version updated from `0.2.3` -> `0.3.0`
> [update] Update nuclei-sdk package version

- ai/Kconfig
- ai/quest/Kconfig
- ai/quest/package.json
Oxford 开源的量子计算机模拟器 (QuEST)
在 RT-Thread 上如果有 RTC 也成功运行了，虽然不知道有没有用，但是可以试试 MCU 能模拟多少个量子比特：
- 嵌入式系统：可以模拟 [ 9, ? ] qbits.
- 普通笔记本：可以模拟 20 qbits.
- GPU 笔记本：可以模拟 28 qbits.
- 服务器集群：可以模拟 45 qbits.
然而 IBM-Q 马上就有 1000 qbits 的量子计算机了.
Example: 3个量子比特电路.
```
msh />quest_tutorial
-------------------------------------------------------
Running QuEST tutorial:
Basic circuit involving a system of 3 qubits.
-------------------------------------------------------
This is our environment:
QUBITS:
Number of qubits is 3.
Number of amps is 8.
Number of amps per rank is 8.
EXECUTION ENVIRONMENT:
Running locally on one node
Number of ranks is 1
OpenMP disabled
Precision: size of qreal is 8 bytes
Circuit output:
Probability amplitude of |111>: 0.112422
Probability of qubit 2 being in state 1: 0.749178
Qubit 0 was …
```
> [ai][quest] new package quest - Quantum Computer Simulator

- peripherals/Kconfig
- peripherals/libnfc/Kconfig
- peripherals/libnfc/package.json
- peripherals/mfoc/Kconfig
- peripherals/mfoc/package.json
Ubuntu 下的 NFC 软件包和加密破解软件包。
- libnfc 1.7.1
```
\ | /
/ | \     4.0.3 build Mar 21 2021
2006 - 2021 Copyright by rt-thread team
msh />
msh />nfc_read_tag
nfc_read_tag uses libnfc 1.7.1
NFC reader: uart2 opened
The following (NFC) ISO14443A tag was found:
ATQA (SENS_RES): 00  04  
UID (NFCID1): 39  e9  af  02  
SAK (SEL_RES): 08  
msh />
```
- mfoc
> Peripheral nfc tools

- peripherals/sensors/Kconfig
- peripherals/sensors/lsm6dsm/Kconfig
- peripherals/sensors/lsm6dsm/package.json
LSM6DSM是STMicroelectronics推出的iNEMO 6DoF惯性测量单元（IMU），用于具有OIS / EIS和AR/VR系统的智能手机。超低功耗、高精度和稳定性，配备 3D 数字加速度计和 3D 数字陀螺仪，在高性能模式下以 0.65 mA 的速度工作，并始终启用低功耗功能，为消费者提供最佳的运动体验。
详细参考：[https://www.st.com/zh/mems-and-sensors/lsm6dsm.html](https://www.st.com/zh/mems-and-sensors/lsm6dsm.html)
- 通讯接口
- 支持的功能
**适配情况**
| 功能         | 加速度计 | 陀螺仪 | 计步 | 温度 |
| ---------------- | -------- | ------ | ------ | ------ |
| **工作模式**     |          |        |        |        |
| 轮询             | √        | √      | √      | √ |
| 中断             |          |        |        |        |
| FIFO             |          |        |        |        |
| **电源模式**     |          |        |        |        |
| 掉电             | √        | √      | √（加速度计掉电） | √（加速度计掉电） |
| 低功耗           | √ | √ | √（加速度计低功耗） | √（加速度计低功耗） |
| 普通 …
> 添加ST(意法半导体)的LSM6DSM传感器驱动包

- peripherals/kobuki/Kconfig
现在应当不需要树莓派，只用 RT-Thread 就可以造一个 ROS 机器人小车了
- Kobuki 软件包可以发布 /odometry 定位
- rplidar 软件包可以发布 /scan 激光雷达
- rosserial 软件包可以 UART/TCP 和 ROS 通信
> [peripherals][kobuki] add get odometry example

- peripherals/Kconfig
- peripherals/micro_ros/Kconfig
- peripherals/micro_ros/package.json
MicroROS 在 RTT 的移植: https://micro.ros.org/
这下 ROS1 (rosserial) 和 ROS2 (uROS) 都支持了。
> [peripherals][micro_ros] new package micro_ros

- peripherals/micro_ros/Kconfig
- peripherals/micro_ros/package.json
- ROS2 (micro_ros) 增加 5 个例程：
- micro_ros_sub_int32: 订阅 INT32 topic
- micro_ros_sub_twist: 订阅 cmd_vel topic
- micro_ros_add_ints_service: 发布加法 service
- micro_ros_deinitialization: 删除节点
- micro_ros_kobuki_control: 控制 kobuki 机器人
- 增加 ROS2 Galactic 支持
- 默认使用 Foxy
- 默认使用 serial
> [peripherals][micro_ros] add more examples

- system/acceleration/rt_memcpy_cm/Kconfig
选定本软件包后自动定义RT_USING_ASM_MEMCPY，用于通知其他程序可以使用加速版本的memcpy
> [rt_memcpy_cm] 增加RT_USING_ASM_MEMCPY宏定义

- misc/entertainment/Kconfig
- misc/mcurses/Kconfig
重新整理了一下entertainment下软件包的排序，人们在linux耳熟能详的或者是有些实际功能的放在前面，游戏什么的放在后面。
entertainment下的软件包对于软件工程开发虽然没有什么用，但是对于初学者趣味化体验rtt操作系统以及rtt软件包生态非常重要。是rtt海外推广时的一个重要部分。
> 将cmatrix从mcurses软件包移除，后续会独立出一个软件包

- system/Kconfig
- system/mcuboot/Kconfig
- system/mcuboot/package.json
添加 mcuboot 的测试 demo package.在 ART-PI 测试可以实现:
*  image 的格式识别,以及在 primary slot 的跳转
*  iamge 从 secondray slot 以 MCUBOOT_OVERWRITE_ONLY 模式更新到 primary slot.
* 支持对 image  RSA 2048 格式打签以及识别
测试视频:
配置截图:
> Add MCUboot package

- peripherals/i2c-tools/Kconfig
RT-Thread Studio 里如果 i2c-tools 没有使用 libc 链接会报错.
> [peripherals][i2c-tools] select libc

- peripherals/Kconfig
- peripherals/Misaka_AT24CXX/Kconfig
- peripherals/Misaka_AT24CXX/package.json
原有的AT24CXX不带页写算法，原版主也联系不上了，干脆自己补充一个好了
> 新增御坂网络AT24CXX驱动

- peripherals/rosserial/Kconfig
突然发现，以前写的软件包很多软件包都没有选择 libc，导致编译报错。
> [peripherals][rosserial] select libc

- multimedia/u8g2/u8g2-official/Kconfig
Upstream 的 u8g2 不需要判断以前软件包的版本号了，忘记删掉了。
> [multimedia][u8g2] Remove legacy version

- iot/webclient/Kconfig
you should choose the laster of "webclient" when you choose the laster of "ota_downloader".
https://github.com/RT-Thread-packages/webclient/pull/76
> [fix] 在没有释出版本之前，ota_downloader 的最新代码应该匹配 webclient 的最新代码，因为引用了 webclient 中最新实现的一个函数。

- tools/fdt/package.json
重新指定v1.0.0,并确定为dfs_posix接口兼容版本,往后版本都将为使用posix接口版本
> [tools/fdt] update version 1.0.0

- security/Kconfig
- security/libhydrogen/Kconfig
- security/libhydrogen/package.json
之前移植 `libsodium` 的时候，感觉它更适合 unix 系列，`libhydrogen` 更适合嵌入式
- Add crypto library [libhydrogen](https://github.com/jedisct1/libhydrogen)
> [security] Add package libhydrogen

- security/libhydrogen/Kconfig
libhydrogen 添加几个基本例程：
- 添加随机数例程 u32, uniform
- 添加 short hash 例程
> [security][libhydrogen] Add rng and hash examples

- misc/Kconfig
- misc/slcan2rtt/Kconfig
- misc/slcan2rtt/package.json
Add package slcan2rtt
这是一个在 RT-Thread 上，用于实现slcan协议的软件包 。基于RT-Thread的device框架实现 can和serial端口的数据转换功能。
> [misc] Add package slcan2rtt

- security/libsodium/Kconfig
- security/libsodium/package.json
最近移植完 libhydrogen，发现 libsodium 并不适合 MCU。
- 官方文档不建议在 Cortex-M0 M3 M4 的 CPU 上运行 https://doc.libsodium.org/installation#cross-compiling
- 安全的随机数生成器 CSPRNG 在 MCU 上没有经过完整的测试
- 整体代码设计都是针对 unix 系统
- 原作者发布了适合 MCU 的版本 libhydrogen
因此在 MCU 上跑 libsodium 可能会带来安全隐患，建议使用 libhydrogen 替代
刚好昨天阿满把 libsodium-legacy 仓库设置为 archive 了。
> [security][libsodium] legacy - use libhydrogen instead

- peripherals/wk2124/Kconfig
v2.0及latest版本也应该支持晶振频率设置，而不是固定为默认频率
> 恢复所有版本支持晶振频率选择

- multimedia/LVGL/gui_guider_demo/Kconfig
Only one version is supported. Remove the check.
Fix below error:
> pkgs --update
Traceback (most recent call last):
File "...\tools\ConEmu\ConEmu\..\..\..\tools\scripts\env.py", line 126, in <module>
main()
File "...\tools\ConEmu\ConEmu\..\..\..\tools\scripts\env.py", line 122, in main
args.func(args)
File "...\tools\scripts\cmds\cmd_package\__init__.py", line 44, in run_env_cmd
package_update()
File "...\tools\scripts\cmds\cmd_package\cmd_package_update.py", line 831, in package_update
if not install_packages(sys_value, force_update):
File "...\tools\scripts\cmds\cmd_package\cmd_package_update.py", line 781, in install_packages
if install_package(env_root, pkgs_root, bsp_root, package, force_update):
File "...\tools\scripts\cmds\cmd_package\cmd_package_update.py", line 254, in …
> gui_guider_demo: fix pkg version

- misc/Kconfig
- misc/soem/Kconfig
- misc/soem/package.json
新增Soem (Source Open EtherCAT Master) 库和例程，并用汇川 IS620N伺服进行了测试
> [misc]Add soem

- peripherals/Kconfig
- peripherals/raspberrypi-pico-sdk/Kconfig
- peripherals/raspberrypi-pico-sdk/package.json
合并之后把主仓库pico里的sdk摘出来，占了一大堆的空间，还不是最新版本的
> add pico sdk

- multimedia/mp3player/Kconfig
修复 mp3player 软件包编译时出现的 fatal error: optparse.h: No such file or directory 错误，添加 optparse 软件包依赖。
> [mp3player] add optparse dependency

- peripherals/micro_ros/Kconfig
**开源之夏 OSPP 2022 - MicroROS on RT-Thread**：
感谢 @navy-to-haijun 同学的贡献，micro_ros 在 RTT 上有了更好的支持：
- 修复了原来 UDP 通信 Segment Fault 的问题；
- 支持从源码编译 microros （只支持 linux 环境）；
- 增加了 ping pong 和 pub sub 例程；
- 增加了不同版本编译器的支持 gcc-5 和 gcc-10；
不过 upstream 到 micro_ros 官仓之前，我还要做一些测试，因为新版本 ROS2 默认的 DDS 从 FastDDS 变成了  CycloneDDS。
> [peripherals][micro_ros] Fix UDP bug and add standalone version

- peripherals/micro_ros/Kconfig
- peripherals/micro_ros/package.json
在 KConfig 里增加限制：micro_ros 从源码编译只支持 gcc-10。
- [修复] galactic-standalone 和 humble-standalone 只支持 gcc-10
> [peripheral][micro_ros] Add support for gcc-10 standalone for galactic and humble

- iot/netutils/Kconfig
- iot/pahomqtt/Kconfig
- peripherals/kendryte-sdk/K210-SDK/kendryte-sdk/Kconfig
- peripherals/rc522/Kconfig
- peripherals/sensors/aht10/Kconfig
- peripherals/sensors/ap3216c/Kconfig
- peripherals/sensors/mpu6xxx/Kconfig
针对Kconfig文件下，需要注意choice选择块内，不可再包含if块，否则在Kconfig-C版本前端中无法正确识别（python前端可以正确识别 https://github.com/RT-Thread/packages/issues/1564
> [kconfig] choice语法块中不可再包含if语法块

- peripherals/wm_libraries/Kconfig
- peripherals/wm_libraries/package.json
wm_libraries目前似乎仅支持m3核，使用RTT软件包测试工具时无法通过，此处添加Kconfig依赖项，对非m3核bsp不做该软件包的使用
> [0 error pkg] 软件包wm_libraries修复

- arduino/devicecontrol/Adafruit-DS3502/Kconfig
- peripherals/micro_ros/Kconfig
- security/mbedtls/Kconfig
修复了micro_ros因Kconfig语法问题导致无法选择package version的bug。
其余是scons --menuconfig时看到的多出空格的小问题。
> micro_ros Kconfig中Version部分的bug修复

- system/TinyUSB/Kconfig
- system/TinyUSB/package.json
发布修复版本。
[Release Note](https://github.com/RT-Thread-packages/tinyusb/releases/tag/0.13.1)
> release TinyUSB 0.13.1

- .github/workflows/action.yml
- .github/workflows/pkgs-test.yml
目前的软件包测试只有当软件包发生更改时（push或pull_request）对改动的部分进行测试，
在此基础上**添加了定时执行的针对全部软件包的测试**。
1. 每个job单独测试一个rt-thread版本一个bsp，总计有6个job。
> rt-thread：
> 1. master
> 2. v4.1.1
> bsp：
> 1. qemu-vexpress-a9
> 2. stm32h750-artpi
> 4. k210
2. 测试结束后将测试报告发布到githubpage页面上面。这里需要开启Pages并且选择来源，我自己的仓库是这样的
> 预计的页面地址在 https://rt-thread.github.io/packages/ ，我这里有个例子https://vacabun.github.io/packages/
3. 每次生成的测试结果报告会和旧的测试结果合并（通过从githubpage获取旧的）。
> 对于冲突问题，通过github actions的concurrency限制了workflow的并发数，当触发新的会等待旧的运行结束。
4. 此外发布了一个包含测试结果的json，名字叫`pkgs_res.json`，如果有其他地方想要获取软件包测试的结果可以从这里读取。
> 这里有一个例子 https://vacabun.github.io/packages/pkgs_res.json
5. 同时针对全部软件包的测试也增加了手动触发方式（workflow_dispatch）。
最后**总结说明**一下，对于软件包测试分为两种情况：
1. 软件包发生更改时（push、pull_request）对改动的部分进行测试。
2. 定时或手动（workflow_dispatch、schedule）执行的针对全部软件包的测试。
> [Actions]Add test all packages.

- .github/workflows/pkgs-test.yml
问题：https://github.com/RT-Thread/packages/pull/1647
没有仓库权限的开发者提交pr检查的时候无法发布github pages。
解决：
pr最后合并的时候Actions的触发来源是push。
所以将pr和push分开，仅在push的时候才发布github pages。
这样仅在合并的时候才更新github pages。
> [Actions] fix pkgs_test deploy permission.

- iot/Kconfig
- iot/lhc_modbus/Kconfig
- iot/lhc_modbus/package.json
添加一个软件包“lhc_modbus”的索引到package仓库，需要管理人员批准一下工作流。
> add lhc-modbus package index

- peripherals/touch/Kconfig
- peripherals/touch/cst812t/Kconfig
- peripherals/touch/cst812t/package.json
[add package] cst812t capacitive touch package for RT-Thread 2.0 inch TrackPad.
> [add package] cst812t capacitive touch package.

- iot/netutils/Kconfig
aarch64平台iperf栈大小需大于2048，否则栈溢出
关联pr: https://github.com/RT-Thread-packages/netutils/pull/98
> add configure of iperf stack size

- system/TinyUSB/Kconfig
the speedmode should be use the below value
from latest version
https://github.com/RT-Thread-packages/tinyusb/blob/e253d517f0d308e6c072afb6e7952112f3e0d1f9/src/tusb_option.h#L203C1-L206C55
> fix speedmode value of tinyusb

- peripherals/sensors/dht11/Kconfig
Adjust the structure of the sensor software package and divide it into two versions: Sensor framework driver and driver framework driver. The sensor version driver is used only after the user opens the sensor framework, and the driver examples of the two versions are provided.
> [sensor] sensor mode separation

- tools/Kconfig
- tools/RVBacktrace/Kconfig
- tools/RVBacktrace/package.json
提交RVBacktrace软件包，一个极简RISC-V栈回溯组件
> [add] 提交RVBacktrace软件包

- peripherals/Kconfig
- peripherals/gc9a01/Kconfig
- peripherals/gc9a01/package.json
RT-Thread package for working with TFT LCD based on  SPI, the IC is gc9a01.
> [peripherals] add a new software package rtt-gc9a01 in peripherals

- peripherals/sensors/mlx90392/package.json
mlx90392 仓库地址不存在 master ，更改为main
> [respository] modify master to main which not have master

- iot/ppp_device/Kconfig
https://github.com/RT-Thread-packages/ppp_device/issues/24
> [ppp_device]修改Kconfig文件中选择模块类型方式

- peripherals/Kconfig
- peripherals/mm32/Kconfig
- peripherals/mm32/package.json
add mm32 soc library for rt-thread.
> mm32 package

- peripherals/hal-sdk/Kconfig
- peripherals/hal-sdk/hc32/Kconfig
- peripherals/hal-sdk/hc32/hc32f334_ddl/Kconfig
- peripherals/hal-sdk/hc32/hc32f334_ddl/package.json
- peripherals/hal-sdk/hc32/hc32f4a8_ddl/Kconfig
- peripherals/hal-sdk/hc32/hc32f4a8_ddl/package.json
Add the indexes of hc32f4a8 and hc32f334 package repositories.
> [hc32] Add the indexes of hc32f4a8 and hc32f334 package repositories.

- peripherals/hal-sdk/nxp/Kconfig
- peripherals/hal-sdk/nxp/nxp-imx6sx-sdk/Kconfig
- peripherals/hal-sdk/nxp/nxp-imx6sx-sdk/package.json
- peripherals/hal-sdk/nxp/nxp-imx6ul-sdk/Kconfig
- peripherals/hal-sdk/nxp/nxp-imx6ul-sdk/package.json
- peripherals/hal-sdk/nxp/nxp-imxrt-sdk/Kconfig
- peripherals/hal-sdk/nxp/nxp-imxrt-sdk/package.json
其中包含的对应软件包仓库:
https://github.com/RT-Thread-packages/nxp-imx6sx-sdk/pull/1
https://github.com/RT-Thread-packages/nxp-imx6ul-sdk/pull/1
https://github.com/RT-Thread-packages/nxp-imxrt-sdk/pull/1
> add nxp_imx的软件包仓库索引

- peripherals/Kconfig
- peripherals/sean_ws2812b/Kconfig
- peripherals/sean_ws2812b/package.json
新增 sean_ws2812b 灯带驱动软件包，基于 SPI 接口控制 WS2812B RGB 灯带，适用于 RT-Thread 4.1.0 系统。
该软件包体积小巧、接口规范、功能完整，支持单颗灯珠控制、批量设置、全局亮度调整以及内置 Gamma 校正。
- 支持通过 SPI 接口控制 WS2812B 灯带
- 支持单颗灯珠独立设置颜色
- 支持批量设置所有灯珠颜色
- 支持全局亮度调节（0~255）
- 支持 Gamma 矫正，亮度更自然
- 提供基础灯效示例（如流水灯、呼吸灯）
- 支持 Kconfig 配置 SPI 总线、设备名称、片选引脚、灯珠数量等参数
- 提供详细的 README.md 使用说明文档
- 当前版本基于 RT-Thread 4.1.0 设计
- 实测平台：
- STM32F103（主频48MHz）运行正常
- STM32H743（主频68MHz）运行正常
- 需要在 RT-Thread `menuconfig` 中开启 SPI 驱动（RT_USING_SPI）
- 在工程 `board.h` 文件中取消注释对应的 SPI 总线宏
- 在 STM32CubeMX 中配置 SPI 接口为 "半双工单向发送（Transmit Only Half Duplex）" 模式
详细使用方法和注意事项请参考软件包自带的 [README.md](https://github.com/godmial/sean_ws2812b#readme)。
本软件包遵循 Apache-2.0 许可证。
---
> 新增 sean_ws2812b 软件包

- peripherals/Kconfig
- peripherals/ic74hc165/Kconfig
- peripherals/ic74hc165/package.json
本 PR 提交了 ic74hc165 软件包，用于驱动并行输入串行输出芯片 74HC165，支持：
- GPIO 或 SPI 模式（通过 Kconfig 二选一）
- 多片级联读取
- 可选 CLK_INH 引脚控制
- 示例线程代码（可选启用）
软件包已在以下平台实测通过 GPIO/SPI 模式运行：
- STM32F103RCT6（RT-Thread 4.1.0 / 5.1.0）
- STM32L431RCT6（RT-Thread 4.1.0 / 5.1.0）
感谢审核！
> 新增74HC165驱动

- peripherals/sensors/df220/Kconfig
- peripherals/sensors/df220/package.json
- peripherals/sensors/gy271/Kconfig
- peripherals/sensors/gy271/package.json
- peripherals/sensors/hdc1000/Kconfig
- peripherals/sensors/hdc1000/package.json
- peripherals/sensors/hmc5883/Kconfig
- peripherals/sensors/hmc5883/package.json
> migrate the software package repository

- peripherals/Kconfig
- peripherals/ST7789_SPI/Kconfig
- peripherals/ST7789_SPI/package.json
> add ST7789_SPI package

- peripherals/sensors/bmi088/Kconfig
修复PKG_BMI088_USING_SAMPLE宏缺失导致bmi088/samples/bmi088_sample.c未加入构建的问题
> [peripherals/sensors/bmi088] 修复PKG_BMI088_USING_SAMPLE宏缺失
